const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const demo = {
  business:{name:'Studio Salvadore Salon & Spa',category:'Beauty salon & spa',phone:'+91 98765 43210',email:'hello@studiosalvadore.com',address:'Kolkata, West Bengal',website:'https://studiosalvadore.com',reviewUrl:'',hours:'Mon–Sun · 10:00 AM–8:00 PM',description:'A modern salon and spa creating confident looks and restorative experiences.',tone:'Warm, premium, approachable'},
  leads:[
    {name:'Ananya Sen',source:'Instagram',service:'Hair colour',status:'New',date:'22 Aug'},
    {name:'Riya Kapoor',source:'Google',service:'Bridal package',status:'Follow-up',date:'21 Aug'},
    {name:'Meera Das',source:'Referral',service:'Spa ritual',status:'Booked',date:'20 Aug'},
    {name:'Sneha Roy',source:'Website',service:'Haircut',status:'New',date:'19 Aug'}
  ],
  posts:[
    {title:'Monsoon Hair Rescue',channel:'Instagram',status:'Scheduled',date:'24 Aug · 6:30 PM',theme:'alt'},
    {title:'Bridal Glow Package',channel:'Facebook',status:'Draft',date:'26 Aug · 11:00 AM',theme:''},
    {title:'Self-care Sunday',channel:'Google Business',status:'Ready',date:'31 Aug · 9:00 AM',theme:'third'}
  ],
  appointments:[
    {customer:'Priya Shah',service:'Hair spa',staff:'Anika',date:'2026-08-28T10:00',value:1800,status:'Confirmed'},
    {customer:'Riya Kapoor',service:'Bridal consultation',staff:'Maria',date:'2026-08-28T12:30',value:2500,status:'Confirmed'},
    {customer:'Meera Das',service:'Aroma therapy',staff:'Sumi',date:'2026-08-28T15:00',value:2400,status:'Confirmed'},
    {customer:'Arjun Bose',service:'Haircut',staff:'Ryan',date:'2026-08-28T17:30',value:1500,status:'Pending'}
  ]
};
let state = JSON.parse(localStorage.getItem('marketingmind-state') || 'null') || demo;
state.localSeoChecks ||= [true,true,true,true,true,true,false,false];
state.appointments ||= structuredClone(demo.appointments);
state.business.reviewUrl ||= '';
state.business.hours ||= 'Mon–Sun · 10:00 AM–8:00 PM';
state.usage ||= [];
const save=()=>localStorage.setItem('marketingmind-state',JSON.stringify(state));
const logUsage=(action,credits=1)=>{state.usage.unshift({date:new Date().toLocaleString(),action,credits});state.usage=state.usage.slice(0,100);save()};
const nav=[
  ['Workspace',[['dashboard','⌂','Overview'],['planner','▦','Content planner'],['scheduler','◷','Social scheduler'],['generator','✦','AI generator']]],
  ['Growth',[['seo','⌁','SEO audit'],['local','⌖','Local SEO'],['analytics','↗','Analytics'],['predictions','⌁','Charts & predictions']]],
  ['Relationships',[['crm','♙','CRM'],['appointments','◫','Appointments']]],
  ['System',[['credits','◉','Credits & usage'],['settings','⚙','Business settings']]]
];
const titles={dashboard:'Overview',planner:'Content planner',scheduler:'Social scheduler',generator:'AI content generator',seo:'SEO audit',local:'Local SEO checklist',analytics:'Analytics overview',predictions:'Charts & predictions',crm:'CRM',appointments:'Appointments',credits:'Credits & usage',settings:'Business settings'};

function renderNav(){ $('#mainNav').innerHTML=nav.map(([label,items])=>`<div class="nav-label">${label}</div>${items.map(([r,i,t])=>`<button class="nav-item" data-route="${r}"><span class="nav-icon">${i}</span><span>${t}</span>${r==='crm'?'<span class="nav-badge">4</span>':''}</button>`).join('')}`).join(''); }
function heading(eye,title,desc,actions=''){return `<div class="page-heading"><div><div class="eyebrow">${eye}</div><h1>${title}</h1><p>${desc}</p></div>${actions?`<div class="heading-actions">${actions}</div>`:''}</div>`}
function stat(label,value,trend,icon='↗'){return `<div class="stat-card"><div class="stat-top"><span>${label}</span><span class="stat-icon">${icon}</span></div><div class="stat-value">${value}</div><div class="trend ${trend.includes('this')?'':'neutral'}">${trend}</div></div>`}
function dashboard(){let scheduled=state.posts.filter(p=>p.status==='Scheduled').length,newLeads=state.leads.filter(l=>l.status==='New').length,bookings=state.appointments.filter(a=>a.status!=='Cancelled').length,localScore=Math.round(state.localSeoChecks.filter(Boolean).length/state.localSeoChecks.length*100);return `${heading('Good morning','Your marketing, in one calm place.','Here’s what is moving for Studio Salvadore today.','<button class="ghost-button" data-route="analytics">View report</button><button class="primary-button" data-action="create-content">+ New content</button>')}
<div class="grid stats-grid">${stat('Local profile',`${localScore}%`,'Saved checklist progress','✓')}${stat('Scheduled posts',String(scheduled),'Publishing queue','◷')}${stat('New leads',String(newLeads),'Current pipeline','♙')}${stat('Appointments',String(bookings),'Active bookings','⌖')}</div>
<div class="grid dashboard-grid"><div>
  <section class="card"><div class="card-header"><div><h2 class="card-title">Performance snapshot</h2><p class="card-subtitle">Website visits vs. profile actions · last 7 days</p></div><button class="text-button" data-route="analytics">Details →</button></div><div class="bar-chart">${[42,58,49,74,64,81,70].map((h,i)=>`<div class="bar-group"><span class="bar" style="height:${h*.72}%"></span><span class="bar orange" style="height:${h}%"></span></div>`).join('')}</div><div class="chart-labels">${['Sat','Sun','Mon','Tue','Wed','Thu','Fri'].map(x=>`<span>${x}</span>`).join('')}</div></section>
  <div class="grid quick-actions"><button class="quick-action" data-route="generator"><span>✦</span><strong>Generate a post</strong><small>On-brand copy in seconds</small></button><button class="quick-action" data-route="seo"><span>⌁</span><strong>Run SEO audit</strong><small>Find your next quick win</small></button><button class="quick-action" data-route="crm"><span>♙</span><strong>Add a lead</strong><small>Keep every enquiry warm</small></button></div>
</div><div>
  <section class="card"><div class="card-header"><div><h2 class="card-title">Marketing health</h2><p class="card-subtitle">Your setup is looking strong</p></div></div><div class="score-row"><div class="score-ring" style="--score:78"><strong>78</strong></div><div><b>Good foundation</b><p class="card-subtitle">Complete 3 actions to reach “Excellent”.</p></div></div><ul class="checklist"><li><span class="check-dot">✓</span>Business details added</li><li><span class="check-dot">✓</span>Content plan started</li><li><span class="check-dot pending">!</span>Connect Google Business</li><li><span class="check-dot pending">!</span>Add analytics property</li></ul></section>
  <section class="card" style="margin-top:18px"><div class="card-header"><div><h2 class="card-title">Recent activity</h2><p class="card-subtitle">Latest workspace changes</p></div></div><ul class="activity"><li><span class="activity-icon">✦</span><p><b>Post draft created</b><br><small>Monsoon Hair Rescue</small></p><small>12m</small></li><li><span class="activity-icon">♙</span><p><b>New lead captured</b><br><small>Ananya · Instagram</small></p><small>1h</small></li><li><span class="activity-icon">⌁</span><p><b>SEO scan completed</b><br><small>Score improved to 74</small></p><small>3h</small></li></ul></section>
</div></div>`}
function planner(){return `${heading('Plan with purpose','Content planner','Turn business goals into a consistent publishing rhythm.','<button class="ghost-button">Filter</button><button class="primary-button" data-action="create-content">+ Add content</button>')}<div class="calendar-strip">${[['Mon',18],['Tue',19],['Wed',20],['Thu',21],['Fri',22],['Sat',23],['Sun',24]].map(([d,n],i)=>`<div class="calendar-day ${i===4?'active':''}">${d}<strong>${n}</strong></div>`).join('')}</div><div class="grid module-grid">${state.posts.map((p,i)=>`<article class="card content-card"><div class="content-preview ${p.theme}"><small>${escapeHtml(p.channel)}</small><strong>${escapeHtml(p.title)}</strong></div><div class="content-body"><span class="pill ${p.status==='Scheduled'?'green':p.status==='Draft'?'orange':'blue'}">${p.status}</span><div class="content-meta"><span>${escapeHtml(p.date)}</span><button class="text-button" data-edit-post="${i}">Edit</button></div></div></article>`).join('')}</div>`}
function generator(){return `${heading('Create faster','AI content generator','Draft useful, brand-aligned copy locally; review every draft before publishing.')}<div class="grid dashboard-grid"><section class="card"><div class="form-grid"><div class="field"><label>Content type</label><select id="genType"><option>Instagram post</option><option>Google Business update</option><option>Facebook ad</option><option>Blog outline</option></select></div><div class="field"><label>Goal</label><select id="genGoal"><option>Get bookings</option><option>Build awareness</option><option>Promote an offer</option><option>Educate customers</option></select></div><div class="field full"><label>What should this be about?</label><textarea id="genTopic" placeholder="Example: Monsoon hair spa offer, 20% off this weekend">Monsoon hair spa ritual for dry, frizzy hair</textarea></div><div class="field"><label>Tone</label><select id="genTone"><option>${state.business.tone}</option><option>Playful and energetic</option><option>Direct and professional</option></select></div><div class="field"><label>Language</label><select id="genLanguage"><option>English</option><option>Bengali</option><option>Hindi</option></select></div></div><div style="margin-top:17px"><button class="primary-button" id="generateButton">✦ Generate draft</button></div></section><aside class="credit-box"><div class="eyebrow">Free-first mode</div><h2 class="card-title" style="margin-top:8px">Local draft engine</h2><p style="color:#c2bbb2;line-height:1.55">No API key or paid credits are needed. Add a server-side AI provider later for richer variants.</p><div class="progress"><span style="width:14%"></span></div><small>Local generation · estimated API cost ₹0</small></aside></div><section class="card" id="generatedOutput" style="margin-top:18px;display:none"></section>`}
function scheduler(){return `${heading('Publish consistently','Social scheduler','Prepare and manage posts now; connect publishing providers when ready.','<button class="primary-button" data-action="create-content">+ Schedule post</button>')}<div class="grid dashboard-grid"><section class="card"><div class="card-header"><div><h2 class="card-title">Publishing queue</h2><p class="card-subtitle">${state.posts.length} saved item${state.posts.length===1?'':'s'} across every channel</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Post</th><th>Channel</th><th>Publish time</th><th>Status</th><th>Actions</th></tr></thead><tbody>${state.posts.length?state.posts.map((p,i)=>`<tr><td><b>${escapeHtml(p.title)}</b></td><td>${escapeHtml(p.channel)}</td><td>${escapeHtml(p.date)}</td><td><span class="pill ${p.status==='Scheduled'?'green':p.status==='Ready'?'blue':'orange'}">${p.status}</span></td><td><button class="text-button" data-edit-post="${i}">Edit</button> <button class="text-button" data-delete-post="${i}">Delete</button></td></tr>`).join(''):'<tr><td colspan="5">No saved posts. Create your first draft.</td></tr>'}</tbody></table></div></section><aside class="card"><h2 class="card-title">Channels</h2><p class="card-subtitle">Integration-ready placeholders</p>${[['◎','Instagram & Facebook','Meta Graph API'],['G','Google Business','Business Profile API'],['in','LinkedIn','Community API']].map(x=>`<div class="integration"><span class="integration-logo">${x[0]}</span><div><b>${x[1]}</b><p>${x[2]}</p></div><button class="ghost-button" data-action="placeholder">Connect</button></div>`).join('')}</aside></div>`}
function seo(){let checks=[['✓','Title tags','Unique titles found on 8 pages','Passed'],['✓','Mobile viewport','Pages adapt correctly to mobile','Passed'],['!','Meta descriptions','3 pages need stronger descriptions','Improve'],['!','Image alternative text','6 images are missing alt text','Improve'],['×','Sitemap','No live sitemap detected yet','Fix'],['✓','Structured data','LocalBusiness draft is ready','Passed']];return `${heading('Be easier to find','SEO audit','A lightweight launch-readiness check for your website.','<button class="primary-button" id="auditButton">↻ Run audit</button>')}<div class="grid stats-grid">${stat('SEO score','74/100','Good · 6 points available','⌁')}${stat('Passed','11 checks','No action needed','✓')}${stat('Improvements','5 checks','Easy opportunities','!')}${stat('Critical','1 issue','Sitemap not live','×')}</div><section class="card"><div class="card-header"><div><h2 class="card-title">Technical checklist</h2><p class="card-subtitle">Demo results · connect a website URL for a live crawl</p></div></div>${checks.map(([i,t,d,s])=>`<div class="audit-row"><span class="audit-state ${i==='!'?'warn':i==='×'?'bad':''}">${i}</span><div><b>${t}</b><p>${d}</p></div><span class="pill ${s==='Passed'?'green':'orange'}">${s}</span></div>`).join('')}</section>`}
function localSeo(){let items=['Business name matches your storefront','Primary category selected','Phone and opening hours added','Website link uses tracking tags','Services and prices completed','Business description added','20+ authentic customer reviews','Weekly photo or update published'],done=state.localSeoChecks.filter(Boolean).length,score=Math.round(done/items.length*100);return `${heading('Win nearby searches','Google Business & local SEO','Build the signals that help nearby customers discover and trust you.','<button class="ghost-button" data-action="placeholder">Connect Google profile</button>')}<div class="grid dashboard-grid"><section class="card"><div class="card-header"><div><h2 class="card-title">Profile checklist</h2><p class="card-subtitle">${done} of ${items.length} recommended actions complete</p></div><b>${score}%</b></div><div class="progress"><span style="width:${score}%"></span></div><ul class="checklist">${items.map((x,i)=>`<li><button class="check-dot ${state.localSeoChecks[i]?'':'pending'}" data-check="${i}">${state.localSeoChecks[i]?'✓':''}</button><span>${x}</span></li>`).join('')}</ul></section><aside><section class="card"><h2 class="card-title">NAP consistency</h2><p class="card-subtitle">Name, address and phone</p><div style="margin-top:16px"><b>${state.business.name}</b><p class="muted">${state.business.address}<br>${state.business.phone}</p><span class="pill green">Consistent in workspace</span></div></section><section class="card" style="margin-top:18px"><h2 class="card-title">Next best action</h2><p class="muted">Ask three recent customers for a specific, honest Google review.</p><button class="primary-button" data-action="review-link">Create review request</button></section></aside></div>`}
function crm(){let booked=state.leads.filter(l=>l.status==='Booked').length,follow=state.leads.filter(isLeadDue).length,newCount=state.leads.filter(l=>l.status==='New').length,conversion=state.leads.length?Math.round(booked/state.leads.length*100):0;return `${heading('Know every customer','Leads & customers','A simple pipeline for enquiries, follow-ups, and bookings.','<button class="ghost-button" id="exportLeads">Export CSV</button><label class="ghost-button file-button" for="importLeads">Import CSV</label><input id="importLeads" type="file" accept=".csv,text/csv" hidden><button class="primary-button" id="addLead">+ Add lead</button>')}<div class="grid stats-grid">${stat('Follow-ups due',String(follow),follow?'Needs attention':'Nothing overdue','◷')}${stat('New enquiries',String(newCount),'Current pipeline','♙')}${stat('Bookings won',String(booked),`${conversion}% conversion`,'✓')}${stat('Total contacts',String(state.leads.length),'Saved locally','♙')}</div><section class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Customer</th><th>Contact</th><th>Source</th><th>Interested in</th><th>Next follow-up</th><th>Status</th><th>Action</th></tr></thead><tbody>${state.leads.length?state.leads.map((l,i)=>`<tr title="${escapeHtml(l.notes||'')}"><td><b>${escapeHtml(l.name)}</b><br><small class="muted">${escapeHtml(l.date||'')}</small></td><td>${escapeHtml(l.phone||'—')}</td><td>${escapeHtml(l.source)}</td><td>${escapeHtml(l.service)}</td><td>${l.followUp?`<span class="pill ${isLeadDue(l)?'orange':'green'}">${escapeHtml(l.followUp)}${isLeadDue(l)?' · due':''}</span>`:'<span class="muted">Not set</span>'}</td><td><select data-lead-status="${i}"><option ${l.status==='New'?'selected':''}>New</option><option ${l.status==='Follow-up'?'selected':''}>Follow-up</option><option ${l.status==='Booked'?'selected':''}>Booked</option><option ${l.status==='Lost'?'selected':''}>Lost</option></select></td><td><button class="text-button" data-edit-lead="${i}">Edit</button> <button class="text-button" data-delete-lead="${i}">Delete</button></td></tr>`).join(''):'<tr><td colspan="7">No leads yet.</td></tr>'}</tbody></table></div></section>`}
function appointments(){let active=state.appointments.filter(a=>a.status!=='Cancelled'),value=active.reduce((sum,a)=>sum+(Number(a.value)||0),0);return `${heading('Keep the day flowing','Appointments','Manage upcoming customer visits and expected booking value.','<button class="ghost-button" id="exportAppointments">Export CSV</button><button class="primary-button" data-action="appointment">+ New appointment</button>')}<div class="grid stats-grid">${stat('Active bookings',String(active.length),'Confirmed and pending','◫')}${stat('Confirmed',String(active.filter(a=>a.status==='Confirmed').length),'Ready to serve','✓')}${stat('Pending',String(active.filter(a=>a.status==='Pending').length),'Needs confirmation','◷')}${stat('Expected value',`₹${value.toLocaleString('en-IN')}`,'Active appointments','₹')}</div><section class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Date & time</th><th>Customer</th><th>Service</th><th>Staff</th><th>Value</th><th>Status</th><th>Action</th></tr></thead><tbody>${state.appointments.length?state.appointments.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(a=>{let i=state.appointments.indexOf(a);return `<tr><td>${escapeHtml(new Date(a.date).toLocaleString())}</td><td><b>${escapeHtml(a.customer)}</b></td><td>${escapeHtml(a.service)}</td><td>${escapeHtml(a.staff||'Unassigned')}</td><td>₹${Number(a.value||0).toLocaleString('en-IN')}</td><td><select data-appointment-status="${i}"><option ${a.status==='Pending'?'selected':''}>Pending</option><option ${a.status==='Confirmed'?'selected':''}>Confirmed</option><option ${a.status==='Completed'?'selected':''}>Completed</option><option ${a.status==='Cancelled'?'selected':''}>Cancelled</option></select></td><td><button class="text-button" data-edit-appointment="${i}">Edit</button> <button class="text-button" data-delete-appointment="${i}">Delete</button></td></tr>`}).join(''):'<tr><td colspan="7">No appointments saved.</td></tr>'}</tbody></table></div></section>`}
function analytics(){return `${heading('See what is working','Analytics overview','One practical view of reach, action, and revenue.','<button class="ghost-button" data-action="placeholder">Connect Google Analytics</button>')}<div class="grid stats-grid">${stat('Website visits','1,284','↑ 18% this month','↗')}${stat('Profile actions','346','↑ 12% this month','⌖')}${stat('Booking clicks','98','↑ 9% this month','✓')}${stat('Est. revenue','₹64.2K','From tracked bookings','₹')}</div><div class="grid dashboard-grid"><section class="card"><div class="card-header"><div><h2 class="card-title">Growth trend</h2><p class="card-subtitle">Organic visibility · last 7 days</p></div><span class="pill green">+18.4%</span></div><div class="bar-chart">${[35,46,43,60,72,68,86].map(h=>`<div class="bar-group"><span class="bar orange" style="width:100%;height:${h}%"></span></div>`).join('')}</div><div class="chart-labels">${['Sat','Sun','Mon','Tue','Wed','Thu','Fri'].map(x=>`<span>${x}</span>`).join('')}</div></section><aside class="card"><h2 class="card-title">Data sources</h2><p class="card-subtitle">Connect real reporting when ready</p>${[['G','Google Analytics 4','Not connected'],['L','Looker Studio','Template ready'],['G','Google Business','Not connected']].map(x=>`<div class="integration"><span class="integration-logo">${x[0]}</span><div><b>${x[1]}</b><p>${x[2]}</p></div><button class="text-button" data-action="placeholder">Set up</button></div>`).join('')}</aside></div>`}
function predictions(){return `${heading('Plan with confidence','Charts & predictions','Explore likely leads and revenue from your current marketing trend. Forecasts are directional, not guarantees.','<button class="ghost-button" id="exportForecast">Export forecast</button>')}
<section class="card data-import"><div><h2 class="card-title">Historical data</h2><p class="card-subtitle" id="dataSourceLabel">Using Studio Salvadore demo data · import at least 4 monthly rows for your own forecast</p></div><div class="data-import-actions"><button class="text-button" id="downloadTemplate">Download template</button><label class="ghost-button file-button" for="forecastFile">Import CSV</label><input id="forecastFile" type="file" accept=".csv,text/csv" hidden></div></section>
<section class="card forecast-controls" aria-label="Forecast controls"><div class="field"><label for="forecastPeriod">Forecast period</label><select id="forecastPeriod"><option value="3">Next 3 months</option><option value="6" selected>Next 6 months</option><option value="12">Next 12 months</option></select></div><div class="field"><label for="forecastMetric">Primary metric</label><select id="forecastMetric"><option value="leads">Leads</option><option value="revenue">Revenue</option><option value="visits">Website visits</option></select></div><div class="range-field"><label for="budgetLift">Monthly marketing budget <strong id="budgetLiftValue">+20%</strong></label><input type="range" id="budgetLift" min="-20" max="100" step="5" value="20"></div><div class="range-field"><label for="conversionLift">Conversion improvement <strong id="conversionLiftValue">+5%</strong></label><input type="range" id="conversionLift" min="0" max="30" step="1" value="5"></div></section>
<section class="card combined-analysis"><div class="card-header"><div><h2 class="card-title">Combined analysis engine</h2><p class="card-subtitle">Technical signals 55% · business fundamentals 45%</p></div><span class="pill green" id="combinedSignal">Calculating</span></div><div class="analysis-layout"><div class="analysis-score"><div class="score-ring" id="technicalRing" style="--score:0"><strong id="technicalScore">—</strong></div><div><b>Technical analysis</b><p class="card-subtitle">Trend · momentum · volatility · consistency</p><div class="signal-list"><span>Trend <b id="trendSignal">—</b></span><span>Momentum <b id="momentumSignal">—</b></span><span>Risk <b id="volatilitySignal">—</b></span></div></div></div><div class="fundamentals"><div class="fundamental-head"><div><b>Fundamental analysis</b><p class="card-subtitle">Current business quality and demand signals</p></div><strong id="fundamentalScore">—</strong></div><div class="fundamental-inputs"><div class="field"><label for="conversionRate">Lead conversion %</label><input id="conversionRate" type="number" min="0" max="100" value="58"></div><div class="field"><label for="averageValue">Average booking ₹</label><input id="averageValue" type="number" min="0" value="2700"></div><div class="field"><label for="reviewRating">Google rating</label><input id="reviewRating" type="number" min="1" max="5" step="0.1" value="4.6"></div><div class="field"><label for="seoHealth">SEO health /100</label><input id="seoHealth" type="number" min="0" max="100" value="74"></div></div></div></div><div class="analysis-verdict" id="analysisVerdict">Evaluating signals…</div></section>
<div class="grid stats-grid forecast-stats"><div class="stat-card"><div class="stat-top"><span>Predicted leads</span><span class="stat-icon">♙</span></div><div class="stat-value" id="predictedLeads">—</div><div class="trend" id="leadsDelta">—</div></div><div class="stat-card"><div class="stat-top"><span>Predicted revenue</span><span class="stat-icon">₹</span></div><div class="stat-value" id="predictedRevenue">—</div><div class="trend" id="revenueDelta">—</div></div><div class="stat-card"><div class="stat-top"><span>Expected bookings</span><span class="stat-icon">✓</span></div><div class="stat-value" id="predictedBookings">—</div><div class="trend neutral">Based on current close rate</div></div><div class="stat-card"><div class="stat-top"><span>Confidence range</span><span class="stat-icon">±</span></div><div class="stat-value">Medium</div><div class="trend neutral">Demo historical dataset</div></div></div>
<div class="grid prediction-grid"><section class="card"><div class="card-header"><div><h2 class="card-title" id="forecastChartTitle">Lead forecast</h2><p class="card-subtitle">Actual history, baseline, and adjusted scenario</p></div><div class="chart-legend"><span><i class="legend-dot actual"></i>Actual</span><span><i class="legend-dot baseline"></i>Baseline</span><span><i class="legend-dot scenario"></i>Your scenario</span></div></div><div class="svg-chart" id="forecastChart" role="img" aria-label="Historical and predicted marketing performance line chart"></div></section><section class="card"><div class="card-header"><div><h2 class="card-title">Channel contribution</h2><p class="card-subtitle">Predicted lead share next period</p></div></div><div id="channelChart" class="channel-chart" role="img" aria-label="Predicted leads by channel"></div></section></div>
<section class="card" style="margin-top:18px"><div class="card-header"><div><h2 class="card-title">Prediction assumptions</h2><p class="card-subtitle">Transparent rules behind this MVP forecast</p></div></div><div class="assumption-grid"><div><b>Recent trend</b><p>Weighted growth from the latest six months.</p></div><div><b>Budget response</b><p>Each 10% budget change influences reach by roughly 4%.</p></div><div><b>Conversion response</b><p>The conversion slider applies directly to predicted enquiries.</p></div><div><b>Seasonality</b><p>Salon demand lifts around festive and wedding periods.</p></div></div></section>`}
function credits(){let used=state.usage.reduce((sum,row)=>sum+(Number(row.credits)||0),0),limit=100,percent=Math.min(100,Math.round(used/limit*100));return `${heading('Stay in control','Credits & API usage','See how automation and AI usage affect your budget.')}<div class="grid dashboard-grid"><section class="credit-box"><div class="eyebrow">Local allowance</div><div style="font:800 38px Manrope;margin-top:8px">${used} <span style="font-size:16px;color:#aaa">/ ${limit}</span></div><p style="color:#aaa">Local workflow credits</p><div class="progress"><span style="width:${percent}%"></span></div><small>Browser-local tracking · estimated API cost ₹0</small></section><section class="card"><h2 class="card-title">Free-first guardrails</h2><ul class="checklist"><li><span class="check-dot">✓</span>Local generation enabled</li><li><span class="check-dot">✓</span>Usage limit shown at 100</li><li><span class="check-dot">✓</span>No paid API connected</li></ul></section></div><section class="card" style="margin-top:18px"><div class="card-header"><div><h2 class="card-title">Usage history</h2><p class="card-subtitle">Actions recorded in this browser</p></div><button class="text-button" id="clearUsage">Clear history</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Date</th><th>Action</th><th>Provider</th><th>Credits</th></tr></thead><tbody>${state.usage.length?state.usage.map(row=>`<tr><td>${escapeHtml(row.date)}</td><td>${escapeHtml(row.action)}</td><td>Local engine</td><td>${row.credits}</td></tr>`).join(''):'<tr><td colspan="4">No tracked actions yet.</td></tr>'}</tbody></table></div></section>`}
function settings(){let b=state.business,e=escapeHtml;return `${heading('Your business foundation','Business settings','Keep this aligned with your website and Google Business Profile.','<button class="ghost-button" id="exportBackup">Export backup</button><label class="ghost-button file-button" for="importBackup">Import backup</label><input id="importBackup" type="file" accept="application/json,.json" hidden>')}<div class="settings-layout"><aside class="card settings-nav"><button class="active">Business profile</button><button>Brand voice</button><button>Locations</button><button>Integrations</button><button>Team</button></aside><section class="card"><div class="card-header"><div><h2 class="card-title">Business profile</h2><p class="card-subtitle">Used across content, local SEO, and reporting. Your workspace is stored on this device; export a backup before clearing browser data.</p></div></div><form id="settingsForm" class="form-grid"><div class="field full"><label>Business name</label><input name="name" value="${e(b.name)}"></div><div class="field"><label>Category</label><input name="category" value="${e(b.category)}"></div><div class="field"><label>Phone</label><input name="phone" value="${e(b.phone)}"></div><div class="field"><label>Email</label><input name="email" value="${e(b.email)}"></div><div class="field"><label>Website</label><input name="website" value="${e(b.website)}"></div><div class="field"><label>Google review URL</label><input name="reviewUrl" value="${e(b.reviewUrl)}" placeholder="https://g.page/r/…/review"></div><div class="field full"><label>Address / service area</label><input name="address" value="${e(b.address)}"></div><div class="field full"><label>Opening hours</label><input name="hours" value="${e(b.hours)}"></div><div class="field full"><label>Short description</label><textarea name="description">${e(b.description)}</textarea></div><div class="field full"><label>Brand voice</label><input name="tone" value="${e(b.tone)}"></div><div class="field full"><div><button class="primary-button">Save changes</button></div></div></form></section></div>`}
const views={dashboard,planner,scheduler,generator,seo,local:localSeo,analytics,predictions,crm,appointments,credits,settings};
function route(name){name=views[name]?name:'dashboard';location.hash=name;$('#app').innerHTML=views[name]();$('#pageCrumb').textContent=titles[name];$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.route===name));$('#sidebar').classList.remove('open');$('#app').focus();bindPage();}
function toast(msg){let el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2500)}
function modal(title,body,submit='Save'){let d=$('#modal');$('#modalContent').innerHTML=`<div class="modal-head"><h2>${title}</h2><button class="icon-button" value="cancel">×</button></div>${body}<div class="modal-actions"><button class="ghost-button" value="cancel">Cancel</button><button class="primary-button" value="default">${submit}</button></div>`;d.showModal();return d}
function contentModal(){let d=modal('Create content',`<div class="form-grid"><div class="field full"><label>Post idea</label><input id="newTitle" placeholder="What do you want to share?"></div><div class="field"><label>Channel</label><select id="newChannel"><option>Instagram</option><option>Facebook</option><option>Google Business</option></select></div><div class="field"><label>Publish date</label><input id="newDate" type="datetime-local"></div></div>`,'Add to planner');d.onsubmit=e=>{e.preventDefault();let title=$('#newTitle').value.trim();if(!title)return;state.posts.unshift({title,channel:$('#newChannel').value,status:'Draft',date:$('#newDate').value?new Date($('#newDate').value).toLocaleString():'Unscheduled',theme:'alt'});save();d.close();toast('Draft added to your planner');if(location.hash==='#planner')route('planner')};}
function editPostModal(index){let post=state.posts[index];if(!post)return;let d=modal('Edit content',`<div class="form-grid"><div class="field full"><label>Title</label><input id="editPostTitle" value="${escapeHtml(post.title)}" required></div><div class="field"><label>Channel</label><select id="editPostChannel">${['Instagram','Facebook','Google Business','Blog'].map(x=>`<option ${post.channel===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Status</label><select id="editPostStatus">${['Draft','Ready','Scheduled'].map(x=>`<option ${post.status===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field full"><label>Publish date and time</label><input id="editPostDate" type="datetime-local"></div><div class="field full"><label>Copy</label><textarea id="editPostCopy">${escapeHtml(post.copy||'')}</textarea></div></div>`,'Save content');d.onsubmit=e=>{e.preventDefault();let date=$('#editPostDate').value;state.posts[index]={...post,title:$('#editPostTitle').value.trim(),channel:$('#editPostChannel').value,status:$('#editPostStatus').value,date:date?new Date(date).toLocaleString():post.date,copy:$('#editPostCopy').value};save();d.close();route(location.hash.slice(1)||'planner');toast('Content updated')}}
function appointmentModal(){let d=modal('New appointment',`<div class="form-grid"><div class="field"><label>Customer</label><input id="appointmentCustomer" required></div><div class="field"><label>Service</label><input id="appointmentService" required></div><div class="field"><label>Team member</label><input id="appointmentStaff" placeholder="Optional"></div><div class="field"><label>Date and time</label><input id="appointmentDate" type="datetime-local" required></div><div class="field"><label>Estimated value ₹</label><input id="appointmentValue" type="number" min="0" value="0"></div><div class="field"><label>Status</label><select id="appointmentStatus"><option>Pending</option><option>Confirmed</option></select></div><div class="field full"><label><input id="appointmentLead" type="checkbox" checked> Add customer to CRM if not already present</label></div></div>`,'Save appointment');d.onsubmit=e=>{e.preventDefault();let customer=$('#appointmentCustomer').value.trim(),service=$('#appointmentService').value.trim(),staff=$('#appointmentStaff').value.trim(),date=$('#appointmentDate').value;if(hasAppointmentConflict(date,staff)&&!confirm('This team member already has a booking at this time. Save anyway?'))return;state.appointments.push({customer,service,staff,date,value:Math.max(0,Number($('#appointmentValue').value)||0),status:$('#appointmentStatus').value});if($('#appointmentLead').checked&&!state.leads.some(l=>l.name.toLowerCase()===customer.toLowerCase()))state.leads.unshift({name:customer,source:'Appointment',service,status:'Booked',date:'Today'});save();d.close();route('appointments');toast('Appointment saved')}}
function hasAppointmentConflict(date,staff,except=-1){if(!date||!staff)return false;return state.appointments.some((a,i)=>i!==except&&a.status!=='Cancelled'&&a.date===date&&(a.staff||'').toLowerCase()===staff.toLowerCase())}
function editAppointmentModal(index){const item=state.appointments[index];if(!item)return;let d=modal('Edit appointment',`<div class="form-grid"><div class="field"><label>Customer</label><input id="editAppointmentCustomer" value="${escapeHtml(item.customer)}" required></div><div class="field"><label>Service</label><input id="editAppointmentService" value="${escapeHtml(item.service)}" required></div><div class="field"><label>Team member</label><input id="editAppointmentStaff" value="${escapeHtml(item.staff||'')}"></div><div class="field"><label>Date and time</label><input id="editAppointmentDate" type="datetime-local" value="${escapeHtml(item.date)}" required></div><div class="field"><label>Estimated value ₹</label><input id="editAppointmentValue" type="number" min="0" value="${Number(item.value)||0}"></div><div class="field"><label>Status</label><select id="editAppointmentStatus">${['Pending','Confirmed','Completed','Cancelled'].map(x=>`<option ${item.status===x?'selected':''}>${x}</option>`).join('')}</select></div></div>`,'Save changes');d.onsubmit=event=>{event.preventDefault();const date=$('#editAppointmentDate').value,staff=$('#editAppointmentStaff').value.trim();if(hasAppointmentConflict(date,staff,index)&&!confirm('This team member already has a booking at this time. Save anyway?'))return;state.appointments[index]={customer:$('#editAppointmentCustomer').value.trim(),service:$('#editAppointmentService').value.trim(),staff,date,value:Math.max(0,Number($('#editAppointmentValue').value)||0),status:$('#editAppointmentStatus').value};save();d.close();route('appointments');toast('Appointment updated')}}
function isLeadDue(lead){if(!lead.followUp||['Booked','Lost'].includes(lead.status))return false;return lead.followUp<=new Date().toISOString().slice(0,10)}
function editLeadModal(index){const lead=state.leads[index];if(!lead)return;let d=modal('Edit lead',`<div class="form-grid"><div class="field"><label>Name</label><input id="editLeadName" value="${escapeHtml(lead.name)}" required></div><div class="field"><label>Phone</label><input id="editLeadPhone" type="tel" value="${escapeHtml(lead.phone||'')}"></div><div class="field"><label>Source</label><input id="editLeadSource" value="${escapeHtml(lead.source||'')}"></div><div class="field"><label>Next follow-up</label><input id="editLeadFollowUp" type="date" value="${escapeHtml(lead.followUp||'')}"></div><div class="field full"><label>Interested in</label><input id="editLeadService" value="${escapeHtml(lead.service||'')}"></div><div class="field full"><label>Notes</label><textarea id="editLeadNotes">${escapeHtml(lead.notes||'')}</textarea></div></div>`,'Save lead');d.onsubmit=event=>{event.preventDefault();state.leads[index]={...lead,name:$('#editLeadName').value.trim(),phone:$('#editLeadPhone').value.trim(),source:$('#editLeadSource').value.trim()||'Unknown',service:$('#editLeadService').value.trim()||'Not specified',followUp:$('#editLeadFollowUp').value,notes:$('#editLeadNotes').value.trim(),date:'Today'};save();d.close();route('crm');toast('Lead updated')}}
function reviewRequestModal(){let message=`Thank you for visiting ${state.business.name}. If you enjoyed your experience, would you share an honest Google review? Your feedback helps our local team grow. ${state.business.reviewUrl||'[Add your Google review URL in Business settings]'}`,d=modal('Google review request',`<div class="field"><label>Customer message</label><textarea id="reviewMessage" style="min-height:180px">${escapeHtml(message)}</textarea></div><p class="muted">Send only to genuine customers who have used your service. Do not offer incentives for reviews.</p>`,'Copy message');d.onsubmit=e=>{e.preventDefault();navigator.clipboard?.writeText($('#reviewMessage').value);logUsage('Google review request',1);d.close();toast('Review request copied')}}
function createLocalDraft(topic,type,goal,language){
  const business=state.business.name,cta=goal==='Get bookings'?'Book your appointment today.':goal==='Promote an offer'?'Message us to claim the offer.':goal==='Educate customers'?'Save this tip and ask our team what suits you.':'Follow us for more salon and self-care inspiration.';
  if(language==='Bengali')return `${topic} নিয়ে ${business}-এর বিশেষ যত্ন। আপনার চুল, ত্বক ও স্বস্তির প্রয়োজন বুঝে আমাদের টিম ব্যক্তিগতভাবে সেবা সাজায়। আজই যোগাযোগ করে আপনার সময় বুক করুন।\n\n#StudioSalvadore #KolkataSalon #SalonAndSpa`;
  if(language==='Hindi')return `${topic} के लिए ${business} की खास देखभाल। हमारी टीम आपकी ज़रूरत के अनुसार व्यक्तिगत सलाह और सेवा देती है। आज ही अपना अपॉइंटमेंट बुक करें।\n\n#StudioSalvadore #KolkataSalon #SalonAndSpa`;
  if(type==='Blog outline')return `Title: ${topic}\n\n1. Why this matters\n2. Common concerns and mistakes\n3. Professional care options\n4. At-home maintenance tips\n5. When to book a consultation\n\nConclusion: ${cta}`;
  const opener=type==='Facebook ad'?'Ready for a little transformation?':type==='Google Business update'?'Now at Studio Salvadore:':'A little care can change the way your whole week feels. ✨';
  return `${opener}\n\n${topic}. At ${business}, our team combines thoughtful consultation with personalised salon and spa care, so every visit feels confidently yours. ${cta}\n\n#StudioSalvadore #KolkataSalon #SalonAndSpa`;
}
function bindPage(){
  if($('#forecastChart')){
    const defaults={leads:[14,17,19,18,22,24],revenue:[38,42,47,45,55,64],visits:[720,810,870,940,1080,1284]};
    const refreshForecast=()=>{
      const months=Number($('#forecastPeriod').value),budget=Number($('#budgetLift').value),conversion=Number($('#conversionLift').value),metric=$('#forecastMetric').value;
      $('#budgetLiftValue').textContent=`${budget>=0?'+':''}${budget}%`; $('#conversionLiftValue').textContent=`+${conversion}%`;
      const imported=state.forecastData?.[metric],history=imported?.length>=4?imported:defaults[metric],trend=linearTrend(history),base=history.at(-1),growth=Math.max(-.12,Math.min(.2,trend.slope/Math.max(1,base)));
      const config={leads:{label:'Leads',format:n=>Math.round(n)},revenue:{label:'Revenue',format:n=>`₹${Math.round(n)}K`},visits:{label:'Website visits',format:n=>Math.round(n).toLocaleString('en-IN')}}[metric];
      const conversionRate=Math.max(0,Math.min(100,Number($('#conversionRate').value)||0)),averageValue=Math.max(0,Number($('#averageValue').value)||0),reviewRating=Math.max(1,Math.min(5,Number($('#reviewRating').value)||1)),seoHealth=Math.max(0,Math.min(100,Number($('#seoHealth').value)||0));
      const returns=history.slice(1).map((v,i)=>(v-history[i])/Math.max(1,history[i])),momentum=returns.slice(-3).reduce((a,b)=>a+b,0)/Math.max(1,returns.slice(-3).length),meanReturn=returns.reduce((a,b)=>a+b,0)/Math.max(1,returns.length),volatility=Math.sqrt(returns.reduce((a,b)=>a+Math.pow(b-meanReturn,2),0)/Math.max(1,returns.length));
      const technicalScore=Math.round(clamp(50+growth*220+momentum*120-volatility*130,0,100)),fundamentalScore=Math.round(clamp(conversionRate*.35+(averageValue/5000*100)*.2+(reviewRating/5*100)*.25+seoHealth*.2,0,100)),combinedScore=Math.round(technicalScore*.55+fundamentalScore*.45),modelFactor=.85+combinedScore*.003;
      const scenarioFactor=(1+(budget*.004)+(conversion/100))*modelFactor,season=[1.01,1.04,1.02,1.08,1.12,1.06,1.03,1.05,1.1,1.15,1.08,1.04];
      const baseline=Array.from({length:months},(_,i)=>Math.max(0,base*Math.pow(1+growth,i+1)*season[i]));
      const scenario=baseline.map((v,i)=>v*(1+(scenarioFactor-1)*((i+1)/months)));
      drawForecastChart(history,baseline,scenario,config.format,config.label); drawChannelChart(scenario.reduce((a,b)=>a+b,0),budget);
      const leadHistory=state.forecastData?.leads?.length>=4?state.forecastData.leads:defaults.leads,leadTrend=linearTrend(leadHistory),leadGrowth=Math.max(-.12,Math.min(.2,leadTrend.slope/Math.max(1,leadHistory.at(-1)))),leadBase=leadHistory.at(-1)*Math.pow(1+leadGrowth,months)*months,leadScenario=leadBase*scenarioFactor;
      const bookings=leadScenario*(conversionRate/100);$('#predictedLeads').textContent=Math.round(leadScenario); $('#leadsDelta').textContent=`${scenarioFactor>=1?'↑':'↓'} ${Math.abs(Math.round((scenarioFactor-1)*100))}% combined adjustment`; $('#predictedBookings').textContent=Math.round(bookings); $('#predictedRevenue').textContent=`₹${Math.round(bookings*averageValue/1000)}K`; $('#revenueDelta').textContent=`Across ${months} months`; $('#forecastChartTitle').textContent=`${config.label} forecast`;
      $('#technicalScore').textContent=technicalScore;$('#technicalRing').style.setProperty('--score',technicalScore);$('#fundamentalScore').textContent=fundamentalScore;$('#trendSignal').textContent=growth>.03?'Rising':growth<-.02?'Falling':'Stable';$('#momentumSignal').textContent=momentum>.03?'Positive':momentum<-.03?'Negative':'Neutral';$('#volatilitySignal').textContent=volatility>.16?'High':volatility>.08?'Medium':'Low';const signal=combinedScore>=70?'Growth':combinedScore>=50?'Hold & improve':'Caution';$('#combinedSignal').textContent=`${signal} · ${combinedScore}/100`;$('#combinedSignal').className=`pill ${combinedScore>=70?'green':combinedScore>=50?'orange':''}`;$('#analysisVerdict').innerHTML=combinedScore>=70?'<b>Growth opportunity:</b> signals support measured scaling. Keep review velocity and conversion quality stable.':combinedScore>=50?'<b>Balanced outlook:</b> maintain spend and improve conversion or SEO before scaling aggressively.':'<b>Caution:</b> technical weakness and fundamentals do not yet support higher spend. Fix the weakest inputs first.';
    };
    ['forecastPeriod','forecastMetric','budgetLift','conversionLift','conversionRate','averageValue','reviewRating','seoHealth'].forEach(id=>$('#'+id).addEventListener('input',refreshForecast));
    $('#exportForecast').onclick=()=>{const rows=['Metric,Value',`Period,${$('#forecastPeriod').value} months`,`Budget change,${$('#budgetLift').value}%`,`Conversion improvement,${$('#conversionLift').value}%`,`Predicted leads,${$('#predictedLeads').textContent}`,`Predicted revenue,${$('#predictedRevenue').textContent}`];const blob=new Blob([rows.join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='marketingmind-forecast.csv';a.click();URL.revokeObjectURL(a.href);toast('Forecast exported')};
    $('#downloadTemplate').onclick=()=>downloadText('month,leads,revenue,visits\n2026-01,14,38,720\n2026-02,17,42,810\n2026-03,19,47,870\n2026-04,18,45,940\n2026-05,22,55,1080\n2026-06,24,64,1284','marketingmind-data-template.csv');
    $('#forecastFile').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=parseForecastCsv(reader.result);state.forecastData=parsed.data;state.forecastMonths=parsed.months;save();$('#dataSourceLabel').textContent=`Using ${file.name} · ${parsed.months.length} months imported`;refreshForecast();toast('Historical data imported')}catch(err){toast(err.message)}};reader.readAsText(file)};
    if(state.forecastData)$('#dataSourceLabel').textContent=`Using imported data · ${state.forecastData.leads.length} months saved locally`;
    refreshForecast();
  }
  $('#generateButton')?.addEventListener('click',()=>{let topic=$('#genTopic').value.trim()||'your latest offer',type=$('#genType').value,goal=$('#genGoal').value,language=$('#genLanguage').value,draft=createLocalDraft(topic,type,goal,language),out=$('#generatedOutput'),channel=type.startsWith('Instagram')?'Instagram':type.startsWith('Facebook')?'Facebook':type.startsWith('Google')?'Google Business':'Blog';logUsage(`${type} draft`,1);out.style.display='block';out.innerHTML=`<div class="card-header"><div><h2 class="card-title">Your ${language} draft</h2><p class="card-subtitle">Local output · edit and verify before publishing</p></div><div><button class="ghost-button" id="copyDraft">Copy</button> <button class="primary-button" id="saveDraft">Save to planner</button></div></div><textarea id="draftText" style="width:100%;min-height:190px;font-size:15px;line-height:1.7">${escapeHtml(draft)}</textarea><div class="content-meta" style="margin-top:12px"><span>${type} · ${goal}</span><button class="text-button" id="scheduleDraft">Schedule instead →</button></div>`;$('#copyDraft').onclick=()=>navigator.clipboard?.writeText($('#draftText').value).then(()=>toast('Draft copied'));$('#saveDraft').onclick=()=>{state.posts.unshift({title:topic,copy:$('#draftText').value,channel,status:'Draft',date:'Unscheduled',theme:'alt'});save();toast('Draft saved to planner')};$('#scheduleDraft').onclick=()=>{let d=modal('Schedule generated draft',`<div class="field"><label>Publish date and time</label><input id="draftDate" type="datetime-local" required></div>`,'Schedule');d.onsubmit=e=>{e.preventDefault();state.posts.unshift({title:topic,copy:$('#draftText').value,channel,status:'Scheduled',date:new Date($('#draftDate').value).toLocaleString(),theme:'third'});save();d.close();toast('Post added to publishing queue')}};});
  $('#auditButton')?.addEventListener('click',()=>{toast('Demo audit complete — connect a URL for live results')});
  $('#addLead')?.addEventListener('click',()=>{let d=modal('Add a lead',`<div class="form-grid"><div class="field"><label>Name</label><input id="leadName" required></div><div class="field"><label>Phone</label><input id="leadPhone" type="tel"></div><div class="field"><label>Source</label><select id="leadSource"><option>Google</option><option>Instagram</option><option>Website</option><option>Referral</option></select></div><div class="field"><label>Next follow-up</label><input id="leadFollowUp" type="date"></div><div class="field full"><label>Interested in</label><input id="leadService"></div><div class="field full"><label>Notes</label><textarea id="leadNotes" placeholder="Customer preference, enquiry details, next action…"></textarea></div></div>`,'Add lead');d.onsubmit=e=>{e.preventDefault();state.leads.unshift({name:$('#leadName').value,phone:$('#leadPhone').value,source:$('#leadSource').value,service:$('#leadService').value||'Not specified',followUp:$('#leadFollowUp').value,notes:$('#leadNotes').value,status:$('#leadFollowUp').value?'Follow-up':'New',date:'Today'});save();d.close();route('crm');toast('Lead added')};});
  $('#exportLeads')?.addEventListener('click',()=>{const rows=[['name','phone','source','service','status','date','followup','notes'],...state.leads.map(l=>[l.name,l.phone,l.source,l.service,l.status,l.date,l.followUp,l.notes])];downloadText(rows.map(row=>row.map(csvCell).join(',')).join('\n'),'marketingmind-leads.csv');toast('Leads exported')});
  $('#importLeads')?.addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const imported=parseLeadsCsv(reader.result);state.leads=[...imported,...state.leads];save();route('crm');toast(`${imported.length} leads imported`)}catch(error){toast(error.message)}};reader.readAsText(file)});
  $('#exportAppointments')?.addEventListener('click',()=>{const rows=[['date','customer','service','staff','value','status'],...state.appointments.map(a=>[a.date,a.customer,a.service,a.staff,a.value,a.status])];downloadText(rows.map(row=>row.map(csvCell).join(',')).join('\n'),'marketingmind-appointments.csv');toast('Appointments exported')});
  $('#settingsForm')?.addEventListener('submit',e=>{e.preventDefault();state.business=Object.fromEntries(new FormData(e.currentTarget));save();toast('Business profile saved')});
  $('#exportBackup')?.addEventListener('click',()=>{const backup={app:'MarketingMind AI',version:1,exportedAt:new Date().toISOString(),data:state};downloadText(JSON.stringify(backup,null,2),`marketingmind-backup-${new Date().toISOString().slice(0,10)}.json`);toast('Workspace backup exported')});
  $('#importBackup')?.addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const backup=JSON.parse(reader.result);const incoming=backup?.data||backup;if(!incoming?.business||!Array.isArray(incoming.leads)||!Array.isArray(incoming.posts))throw new Error('This is not a valid MarketingMind backup');state=incoming;state.localSeoChecks||=[true,true,true,true,true,true,false,false];state.appointments||=[];state.usage||=[];save();route('settings');toast('Workspace backup restored')}catch(error){toast(error.message||'Backup could not be imported')}};reader.readAsText(file)});
  $('#clearUsage')?.addEventListener('click',()=>{if(!confirm('Clear local usage history?'))return;state.usage=[];save();route('credits');toast('Usage history cleared')});
  $$('[data-edit-post]').forEach(button=>button.onclick=()=>editPostModal(Number(button.dataset.editPost)));
  $$('[data-delete-post]').forEach(button=>button.onclick=()=>{if(!confirm('Remove this content item?'))return;state.posts.splice(Number(button.dataset.deletePost),1);save();route('scheduler');toast('Content removed')});
  $$('[data-lead-status]').forEach(select=>select.onchange=()=>{state.leads[Number(select.dataset.leadStatus)].status=select.value;state.leads[Number(select.dataset.leadStatus)].date='Today';save();route('crm');toast('Lead status updated')});
  $$('[data-delete-lead]').forEach(button=>button.onclick=()=>{if(!confirm('Remove this lead from the local CRM?'))return;state.leads.splice(Number(button.dataset.deleteLead),1);save();route('crm');toast('Lead removed')});
  $$('[data-edit-lead]').forEach(button=>button.onclick=()=>editLeadModal(Number(button.dataset.editLead)));
  $$('[data-appointment-status]').forEach(select=>select.onchange=()=>{state.appointments[Number(select.dataset.appointmentStatus)].status=select.value;save();route('appointments');toast('Appointment status updated')});
  $$('[data-delete-appointment]').forEach(button=>button.onclick=()=>{if(!confirm('Remove this appointment?'))return;state.appointments.splice(Number(button.dataset.deleteAppointment),1);save();route('appointments');toast('Appointment removed')});
  $$('[data-edit-appointment]').forEach(button=>button.onclick=()=>editAppointmentModal(Number(button.dataset.editAppointment)));
  $$('[data-check]').forEach(b=>b.onclick=()=>{let index=Number(b.dataset.check);state.localSeoChecks[index]=!state.localSeoChecks[index];save();route('local')});
}
function drawForecastChart(history,baseline,scenario,format,label){const el=$('#forecastChart'),w=Math.max(560,el.clientWidth||760),h=310,p={l:58,r:24,t:24,b:42},all=[...history,...baseline,...scenario],min=Math.min(...all)*.88,max=Math.max(...all)*1.1,total=history.length+baseline.length,x=i=>p.l+i*(w-p.l-p.r)/(total-1),y=v=>p.t+(max-v)*(h-p.t-p.b)/(max-min),path=arr=>arr.map((v,i)=>`${i?'L':'M'} ${x(i)} ${y(v)}`).join(' '),futureStart=history.length-1,fullBase=[history.at(-1),...baseline],fullScenario=[history.at(-1),...scenario],ticks=Array.from({length:5},(_,i)=>min+(max-min)*i/4);el.innerHTML=`<svg viewBox="0 0 ${w} ${h}" aria-hidden="true"><rect class="forecast-zone" x="${x(futureStart)}" y="${p.t}" width="${w-p.r-x(futureStart)}" height="${h-p.t-p.b}"></rect>${ticks.map(v=>`<line class="grid-line" x1="${p.l}" y1="${y(v)}" x2="${w-p.r}" y2="${y(v)}"></line><text class="axis-label" x="${p.l-9}" y="${y(v)+4}" text-anchor="end">${format(v)}</text>`).join('')}<line class="axis-line" x1="${p.l}" y1="${h-p.b}" x2="${w-p.r}" y2="${h-p.b}"></line><path class="chart-line actual-line" d="${path(history)}"></path><path class="chart-line baseline-line" d="${fullBase.map((v,i)=>`${i?'L':'M'} ${x(futureStart+i)} ${y(v)}`).join(' ')}"></path><path class="chart-line scenario-line" d="${fullScenario.map((v,i)=>`${i?'L':'M'} ${x(futureStart+i)} ${y(v)}`).join(' ')}"></path>${scenario.map((v,i)=>`<circle class="scenario-point" cx="${x(history.length+i)}" cy="${y(v)}" r="4"><title>Month ${i+1}: ${format(v)} ${label}</title></circle>`).join('')}<text class="axis-caption" x="${p.l}" y="${h-13}">6 months actual</text><text class="axis-caption" x="${w-p.r}" y="${h-13}" text-anchor="end">${baseline.length} months predicted</text><text class="forecast-label" x="${x(futureStart)+10}" y="${p.t+17}">FORECAST</text></svg>`}
function drawChannelChart(total,budget){const channels=[['Google',.42],['Instagram',.31],['Website',.17],['Referral',.10]],adjust=1+budget*.002;$('#channelChart').innerHTML=channels.map(([name,share])=>{const value=Math.round(total*share*adjust),width=Math.round(share*100);return `<div class="channel-row"><div><b>${name}</b><span>${value} leads · ${width}%</span></div><div class="channel-track"><span style="width:${width}%"></span></div></div>`}).join('')}
function linearTrend(values){const n=values.length,sumX=n*(n-1)/2,sumY=values.reduce((a,b)=>a+b,0),sumXY=values.reduce((a,b,i)=>a+b*i,0),sumXX=values.reduce((a,b,i)=>a+i*i,0),den=n*sumXX-sumX*sumX,slope=den?(n*sumXY-sumX*sumY)/den:0;return {slope,intercept:(sumY-slope*sumX)/n}}
function parseForecastCsv(text){const rows=text.trim().split(/\r?\n/).map(r=>r.split(',').map(v=>v.trim())),headers=rows.shift().map(x=>x.toLowerCase()),required=['month','leads','revenue','visits'];if(!required.every(x=>headers.includes(x)))throw new Error('CSV needs month, leads, revenue and visits columns');if(rows.length<4)throw new Error('Import at least 4 months of data');const index=Object.fromEntries(required.map(x=>[x,headers.indexOf(x)])),data={leads:[],revenue:[],visits:[]},months=[];rows.forEach((row,i)=>{months.push(row[index.month]);['leads','revenue','visits'].forEach(key=>{const value=Number(row[index[key]]);if(!Number.isFinite(value)||value<0)throw new Error(`Invalid ${key} value on row ${i+2}`);data[key].push(value)})});return {months,data}}
function parseCsvLine(line){const cells=[];let value='',quoted=false;for(let i=0;i<line.length;i++){const char=line[i];if(char==='"'&&quoted&&line[i+1]==='"'){value+='"';i++}else if(char==='"'){quoted=!quoted}else if(char===','&&!quoted){cells.push(value.trim());value=''}else value+=char}cells.push(value.trim());return cells}
function parseLeadsCsv(text){const rows=text.trim().split(/\r?\n/).filter(Boolean).map(parseCsvLine),headers=rows.shift()?.map(x=>x.toLowerCase()),required=['name','source','service'];if(!headers||!required.every(x=>headers.includes(x)))throw new Error('CSV needs name, source and service columns');const at=key=>headers.indexOf(key),get=(row,key)=>at(key)>=0?row[at(key)]||'':'',valid=['New','Follow-up','Booked','Lost'];const leads=rows.map((row,index)=>{const name=get(row,'name').trim();if(!name)throw new Error(`Missing name on row ${index+2}`);const status=get(row,'status')||'New';return {name,phone:get(row,'phone'),source:get(row,'source')||'Imported',service:get(row,'service')||'Not specified',status:valid.includes(status)?status:'New',date:get(row,'date')||'Imported',followUp:get(row,'followup'),notes:get(row,'notes')}});if(!leads.length)throw new Error('No lead rows found');return leads}
function csvCell(value){const text=String(value??'');return /[",\n]/.test(text)?`"${text.replaceAll('"','""')}"`:text}
function downloadText(text,name){const type=name.endsWith('.json')?'application/json':'text/csv',blob=new Blob([text],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function clamp(value,min,max){return Math.max(min,Math.min(max,value))}
document.addEventListener('click',e=>{let routeEl=e.target.closest('[data-route]'),action=e.target.closest('[data-action]');if(routeEl){e.preventDefault();route(routeEl.dataset.route)}if(action){let a=action.dataset.action;if(a==='create-content')contentModal();else if(a==='placeholder')toast('Integration placeholder — ready for API connection');else if(a==='review-link')reviewRequestModal();else if(a==='appointment')appointmentModal()}});
$('#menuButton').onclick=()=>$('#sidebar').classList.toggle('open');
$('#collapseButton').onclick=()=>$('#sidebar').classList.toggle('open');
$('#searchButton').onclick=()=>{let d=modal('Jump to a module',`<div class="field"><label>Search workspace</label><input id="quickSearch" autofocus placeholder="Try SEO, CRM, content…"></div><p class="muted">Tip: use the navigation to explore every working MVP screen.</p>`,'Close');d.onsubmit=e=>{e.preventDefault();d.close()}};
window.addEventListener('hashchange',()=>route(location.hash.slice(1)));
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchButton').click()}});
renderNav();route(location.hash.slice(1)||'dashboard');
let installPrompt=null;
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;$('#installApp').hidden=false});
$('#installApp').onclick=async()=>{if(!installPrompt)return;await installPrompt.prompt();installPrompt=null;$('#installApp').hidden=true};
window.addEventListener('appinstalled',()=>toast('MarketingMind installed'));
if('serviceWorker' in navigator&&location.protocol==='https:')navigator.serviceWorker.register('/sw.js').catch(()=>{});

