const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const demo = {
  business:{name:'Studio Salvadore Salon & Spa',category:'Beauty salon & spa',phone:'+91 98765 43210',email:'hello@studiosalvadore.com',address:'Kolkata, West Bengal',website:'https://studiosalvadore.com',reviewUrl:'',hours:'Mon–Sun · 10:00 AM–8:00 PM',description:'A modern salon and spa creating confident looks and restorative experiences.',tone:'Warm, premium, approachable'},
  leads:[
    {name:'Ananya Sen',source:'Instagram',service:'Hair colour',status:'New',date:'22 Aug'},
    {name:'Riya Kapoor',source:'Google',service:'Bridal package',status:'Follow-up',date:'21 Aug'},
    {name:'Meera Das',source:'Referral',service:'Spa ritual',status:'Booked',date:'20 Aug'},
    {name:'Sneha Roy',source:'Website',service:'Haircut',status:'New',date:'19 Aug'}
  ],
  posts:[
    {title:'Monsoon Hair Rescue',channel:'Instagram',status:'Scheduled',date:'24 Aug · 6:30 PM',theme:'alt'},
    {title:'Bridal Glow Package',channel:'Facebook',status:'Draft',date:'26 Aug · 11:00 AM',theme:''},
    {title:'Self-care Sunday',channel:'Google Business',status:'Ready',date:'31 Aug · 9:00 AM',theme:'third'}
  ],
  appointments:[
    {customer:'Priya Shah',service:'Hair spa',staff:'Anika',date:'2026-08-28T10:00',value:1800,status:'Confirmed'},
    {customer:'Riya Kapoor',service:'Bridal consultation',staff:'Maria',date:'2026-08-28T12:30',value:2500,status:'Confirmed'},
    {customer:'Meera Das',service:'Aroma therapy',staff:'Sumi',date:'2026-08-28T15:00',value:2400,status:'Confirmed'},
    {customer:'Arjun Bose',service:'Haircut',staff:'Ryan',date:'2026-08-28T17:30',value:1500,status:'Pending'}
  ]
};
let state = JSON.parse(localStorage.getItem('marketingmind-state') || 'null') || demo;
state.localSeoChecks ||= [true,true,true,true,true,true,false,false];
state.appointments ||= structuredClone(demo.appointments);
state.business.reviewUrl ||= '';
state.business.hours ||= 'Mon–Sun · 10:00 AM–8:00 PM';
state.usage ||= [];
const save=()=>localStorage.setItem('marketingmind-state',JSON.stringify(state));
const logUsage=(action,credits=1)=>{state.usage.unshift({date:new Date().toLocaleString(),action,credits});state.usage=state.usage.slice(0,100);save()};
const nav=[
  ['Workspace',[['dashboard','⌂','Overview'],['planner','▦','Content planner'],['scheduler','◷','Social scheduler'],['generator','✦','AI generator']]],
  ['Growth',[['seo','⌁','SEO audit'],['local','⌖','Local SEO'],['analytics','↗','Analytics'],['predictions','⌁','Charts & predictions']]],
  ['Relationships',[['crm','♙','CRM'],['appointments','◫','Appointments']]],
  ['System',[['credits','◉','Credits & usage'],['settings','⚙','Business settings']]]
];
const titles={dashboard:'Overview',planner:'Content planner',scheduler:'Social scheduler',generator:'AI content generator',seo:'SEO audit',local:'Local SEO checklist',analytics:'Analytics overview',predictions:'Charts & predictions',crm:'CRM',appointments:'Appointments',credits:'Credits & usage',settings:'Business settings'};

function renderNav(){ $('#mainNav').innerHTML=nav.map(([label,items])=>`<div class="nav-label">${label}</div>${items.map(([r,i,t])=>`<button class="nav-item" data-route="${r}"><span class="nav-icon">${i}</span><span>${t}</span>${r==='crm'?`<span class="nav-badge">${state.leads.length}</span>`:''}</button>`).join('')}`).join(''); }
function heading(eye,title,desc,actions=''){return `<div class="page-heading"><div><div class="eyebrow">${eye}</div><h1>${title}</h1><p>${desc}</p></div>${actions?`<div class="heading-actions">${actions}</div>`:''}</div>`}
function stat(label,value,trend,icon='↗'){return `<div class="stat-card"><div class="stat-top"><span>${label}</span><span class="stat-icon">${icon}</span></div><div class="stat-value">${value}</div><div class="trend ${trend.includes('this')?'':'neutral'}">${trend}</div></div>`}
function marketingHealth(){const fields=['name','category','phone','email','address','website','description','hours'],complete=fields.filter(field=>String(state.business[field]||'').trim()).length/fields.length,local=state.localSeoChecks.filter(Boolean).length/state.localSeoChecks.length,hasContent=state.posts.length>0,hasRelationships=state.leads.length>0||state.appointments.length>0,hasAnalytics=!!state.forecastData,score=Math.round(complete*30+local*30+(hasContent?15:0)+(hasRelationships?15:0)+(hasAnalytics?10:0)),checks=[['Complete business profile',complete>=1],['Reach 75% Local SEO readiness',local>=.75],['Create a content plan',hasContent],['Import historical analytics',hasAnalytics]],remaining=checks.filter(([,ok])=>!ok).length;return {score,checks,remaining,label:score>=85?'Excellent foundation':score>=65?'Good foundation':score>=40?'Building momentum':'Setup needed'}}
function dashboard(){let scheduled=state.posts.filter(p=>p.status==='Scheduled').length,newLeads=state.leads.filter(l=>l.status==='New').length,activeAppointments=state.appointments.filter(a=>a.status!=='Cancelled'),bookings=activeAppointments.length,bookingValue=activeAppointments.reduce((sum,a)=>sum+(Number(a.value)||0),0),localScore=Math.round(state.localSeoChecks.filter(Boolean).length/state.localSeoChecks.length*100),visits=(state.forecastData?.visits||[720,810,870,940,1080,1284]).slice(-7),visitLabels=(state.forecastMonths||['Jan','Feb','Mar','Apr','May','Jun']).slice(-visits.length),visitMax=Math.max(...visits,1),recentPost=state.posts[0],recentLead=state.leads[0],nextAppointment=activeAppointments.slice().sort((a,b)=>a.date.localeCompare(b.date))[0];return `${heading('Good morning','Your marketing, in one calm place.',`Here’s what is moving for ${escapeHtml(state.business.name)} today.`,'<button class="ghost-button" data-route="analytics">View report</button><button class="primary-button" data-action="create-content">+ New content</button>')}
<div class="grid stats-grid">${stat('Local profile',`${localScore}%`,'Saved checklist progress','✓')}${stat('Scheduled posts',String(scheduled),'Publishing queue','◷')}${stat('New leads',String(newLeads),'Current pipeline','♙')}${stat('Booking value',`₹${bookingValue.toLocaleString('en-IN')}`,`${bookings} active appointments`,'₹')}</div>
<div class="grid dashboard-grid"><div>
  <section class="card"><div class="card-header"><div><h2 class="card-title">Website visit snapshot</h2><p class="card-subtitle">${state.forecastData?'Imported historical data':'Studio Salvadore demo history · import data in Predictions'}</p></div><button class="text-button" data-route="analytics">Details →</button></div><div class="bar-chart">${visits.map(value=>`<div class="bar-group"><span class="bar orange" style="width:100%;height:${Math.max(5,Math.round(value/visitMax*100))}%" title="${value.toLocaleString('en-IN')} visits"></span></div>`).join('')}</div><div class="chart-labels">${visitLabels.map(x=>`<span>${escapeHtml(x)}</span>`).join('')}</div></section>
  <div class="grid quick-actions"><button class="quick-action" data-route="generator"><span>✦</span><strong>Generate a post</strong><small>On-brand copy in seconds</small></button><button class="quick-action" data-route="seo"><span>⌁</span><strong>Run SEO audit</strong><small>Find your next quick win</small></button><button class="quick-action" data-route="crm"><span>♙</span><strong>Add a lead</strong><small>Keep every enquiry warm</small></button></div>
</div><div>
  ${(health=>`<section class="card"><div class="card-header"><div><h2 class="card-title">Marketing health</h2><p class="card-subtitle">Calculated from your saved workspace readiness</p></div></div><div class="score-row"><div class="score-ring" style="--score:${health.score}"><strong>${health.score}</strong></div><div><b>${health.label}</b><p class="card-subtitle">${health.remaining?`Complete ${health.remaining} action${health.remaining===1?'':'s'} to improve readiness.`:'Core MVP setup is complete.'}</p></div></div><ul class="checklist">${health.checks.map(([label,ok])=>`<li><span class="check-dot ${ok?'':'pending'}">${ok?'✓':'!'}</span>${label}</li>`).join('')}</ul></section>`)(marketingHealth())}
  <section class="card" style="margin-top:18px"><div class="card-header"><div><h2 class="card-title">Workspace snapshot</h2><p class="card-subtitle">Current saved records</p></div></div><ul class="activity"><li><span class="activity-icon">✦</span><p><b>Latest content</b><br><small>${escapeHtml(recentPost?.title||'No content yet')}</small></p><small>${escapeHtml(recentPost?.status||'')}</small></li><li><span class="activity-icon">♙</span><p><b>Latest lead</b><br><small>${escapeHtml(recentLead?`${recentLead.name} · ${recentLead.source}`:'No leads yet')}</small></p><small>${escapeHtml(recentLead?.status||'')}</small></li><li><span class="activity-icon">◫</span><p><b>Next appointment</b><br><small>${escapeHtml(nextAppointment?`${nextAppointment.customer} · ${nextAppointment.service}`:'No active booking')}</small></p><small>${escapeHtml(nextAppointment?new Date(nextAppointment.date).toLocaleDateString():'')}</small></li></ul></section>
</div></div>`}
function planner(){const today=new Date(),days=Array.from({length:7},(_,index)=>{const date=new Date(today);date.setDate(today.getDate()+index);return date}),channels=[...new Set(state.posts.map(post=>post.channel))];return `${heading('Plan with purpose','Content planner','Turn business goals into a consistent publishing rhythm.','<button class="primary-button" data-action="create-content">+ Add content</button>')}<div class="calendar-strip">${days.map((date,index)=>`<div class="calendar-day ${index===0?'active':''}">${date.toLocaleDateString(undefined,{weekday:'short'})}<strong>${date.getDate()}</strong></div>`).join('')}</div><section class="card planner-toolbar"><div class="planner-filters"><label>Status <select id="plannerStatus"><option value="">All statuses</option><option>Draft</option><option>Ready</option><option>Scheduled</option></select></label><label>Channel <select id="plannerChannel"><option value="">All channels</option>${channels.map(channel=>`<option>${escapeHtml(channel)}</option>`).join('')}</select></label></div><small class="muted" id="plannerCount">${state.posts.length} content items</small></section><div class="grid module-grid" id="plannerCards">${state.posts.map((p,i)=>`<article class="card content-card" data-plan-card data-status="${escapeHtml(p.status)}" data-channel="${escapeHtml(p.channel)}"><div class="content-preview ${p.theme}"><small>${escapeHtml(p.channel)}</small><strong>${escapeHtml(p.title)}</strong></div><div class="content-body"><span class="pill ${p.status==='Scheduled'?'green':p.status==='Draft'?'orange':'blue'}">${p.status}</span><div class="content-meta"><span>${escapeHtml(p.date)}</span><button class="text-button" data-edit-post="${i}">Edit</button></div></div></article>`).join('')}</div>`}
function generator(){return `${heading('Create faster','AI content generator','Draft useful, brand-aligned copy locally; review every draft before publishing.')}<div class="grid dashboard-grid"><section class="card"><div class="form-grid"><div class="field"><label>Content type</label><select id="genType"><option>Instagram post</option><option>Google Business update</option><option>Facebook ad</option><option>Blog outline</option></select></div><div class="field"><label>Goal</label><select id="genGoal"><option>Get bookings</option><option>Build awareness</option><option>Promote an offer</option><option>Educate customers</option></select></div><div class="field full"><label>What should this be about?</label><textarea id="genTopic" placeholder="Example: Monsoon hair spa offer, 20% off this weekend">Monsoon hair spa ritual for dry, frizzy hair</textarea></div><div class="field"><label>Tone</label><select id="genTone"><option>${state.business.tone}</option><option>Playful and energetic</option><option>Direct and professional</option></select></div><div class="field"><label>Language</label><select id="genLanguage"><option>English</option><option>Bengali</option><option>Hindi</option></select></div></div><div style="margin-top:17px"><button class="primary-button" id="generateButton">✦ Generate draft</button></div></section><aside class="credit-box"><div class="eyebrow">Free-first mode</div><h2 class="card-title" style="margin-top:8px">Local draft engine</h2><p style="color:#c2bbb2;line-height:1.55">No API key or paid credits are needed. Add a server-side AI provider later for richer variants.</p><div class="progress"><span style="width:14%"></span></div><small>Local generation · estimated API cost ₹0</small></aside></div><section class="card" id="generatedOutput" style="margin-top:18px;display:none"></section>`}
function scheduler(){const channels=[...new Set(state.posts.map(post=>post.channel))];return `${heading('Publish consistently','Social scheduler','Prepare and manage posts now; connect publishing providers when ready.','<button class="ghost-button" id="exportSchedule">Export CSV</button><button class="primary-button" data-action="create-content">+ Schedule post</button>')}<div class="grid dashboard-grid"><section class="card"><div class="card-header"><div><h2 class="card-title">Publishing queue</h2><p class="card-subtitle" id="scheduleCount">${state.posts.length} saved item${state.posts.length===1?'':'s'} across every channel</p></div></div><div class="planner-filters" style="margin-bottom:14px"><label>Status <select id="scheduleStatus"><option value="">All statuses</option><option>Draft</option><option>Ready</option><option>Scheduled</option></select></label><label>Channel <select id="scheduleChannel"><option value="">All channels</option>${channels.map(channel=>`<option>${escapeHtml(channel)}</option>`).join('')}</select></label></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Post</th><th>Channel</th><th>Publish time</th><th>Status</th><th>Actions</th></tr></thead><tbody>${state.posts.length?state.posts.map((p,i)=>`<tr data-schedule-row data-status="${escapeHtml(p.status)}" data-channel="${escapeHtml(p.channel)}"><td><b>${escapeHtml(p.title)}</b></td><td>${escapeHtml(p.channel)}</td><td>${escapeHtml(p.date)}</td><td><span class="pill ${p.status==='Scheduled'?'green':p.status==='Ready'?'blue':'orange'}">${p.status}</span></td><td><button class="text-button" data-edit-post="${i}">Edit</button> <button class="text-button" data-delete-post="${i}">Delete</button></td></tr>`).join(''):'<tr><td colspan="5">No saved posts. Create your first draft.</td></tr>'}</tbody></table></div></section><aside class="card"><h2 class="card-title">Channels</h2><p class="card-subtitle">Integration-ready placeholders</p>${[['◎','Instagram & Facebook','Meta Graph API'],['G','Google Business','Business Profile API'],['in','LinkedIn','Community API']].map(x=>`<div class="integration"><span class="integration-logo">${x[0]}</span><div><b>${x[1]}</b><p>${x[2]}</p></div><button class="ghost-button" data-action="placeholder">Connect</button></div>`).join('')}</aside></div>`}
function seo(){const saved=state.seoAudit,checks=saved?.checks||[['Title tag',true,'Demo title present'],['Meta description',false,'Run a local HTML audit'],['Single H1',true,'Demo structure'],['Mobile viewport',true,'Demo structure'],['Canonical URL',false,'Run a local HTML audit'],['Image ALT text',false,'Run a local HTML audit'],['JSON-LD schema',true,'LocalBusiness draft available']],score=saved?.score??57,passed=checks.filter(([,ok])=>ok).length,improvements=checks.length-passed;return `${heading('Be easier to find','SEO audit','Analyze page HTML locally and keep your latest structural SEO results.','<button class="primary-button" id="auditButton">↻ Run HTML audit</button>')}<div class="grid stats-grid">${stat('SEO score',`${score}/100`,saved?'Latest saved audit':'Starter baseline','⌁')}${stat('Passed',`${passed} checks`,'No action needed','✓')}${stat('Improvements',`${improvements} checks`,'Review recommended','!')}${stat('Last audit',saved?new Date(saved.date).toLocaleDateString():'Not run','Stored on this device','◷')}</div><section class="card"><div class="card-header"><div><h2 class="card-title">Technical checklist</h2><p class="card-subtitle">${saved?'Latest local HTML audit':'Starter baseline · run an audit to replace it'}</p></div></div>${checks.map(([name,ok,detail])=>`<div class="audit-row"><span class="audit-state ${ok?'':'warn'}">${ok?'✓':'!'}</span><div><b>${name}</b><p>${escapeHtml(detail)}</p></div><span class="pill ${ok?'green':'orange'}">${ok?'Passed':'Improve'}</span></div>`).join('')}</section>`}
function localSeo(){let items=['Business name matches your storefront','Primary category selected','Phone and opening hours added','Website link uses tracking tags','Services and prices completed','Business description added','20+ authentic customer reviews','Weekly photo or update published'],done=state.localSeoChecks.filter(Boolean).length,score=Math.round(done/items.length*100);return `${heading('Win nearby searches','Google Business & local SEO','Build the signals that help nearby customers discover and trust you.','<button class="ghost-button" data-action="placeholder">Connect Google profile</button>')}<div class="grid dashboard-grid"><section class="card"><div class="card-header"><div><h2 class="card-title">Profile checklist</h2><p class="card-subtitle">${done} of ${items.length} recommended actions complete</p></div><b>${score}%</b></div><div class="progress"><span style="width:${score}%"></span></div><ul class="checklist">${items.map((x,i)=>`<li><button class="check-dot ${state.localSeoChecks[i]?'':'pending'}" data-check="${i}">${state.localSeoChecks[i]?'✓':''}</button><span>${x}</span></li>`).join('')}</ul></section><aside><section class="card"><h2 class="card-title">NAP consistency</h2><p class="card-subtitle">Name, address and phone</p><div style="margin-top:16px"><b>${state.business.name}</b><p class="muted">${state.business.address}<br>${state.business.phone}</p><span class="pill green">Consistent in workspace</span></div></section><section class="card" style="margin-top:18px"><h2 class="card-title">Next best action</h2><p class="muted">Ask three recent customers for a specific, honest Google review.</p><button class="primary-button" data-action="review-link">Create review request</button></section></aside></div>`}
function crm(){let booked=state.leads.filter(l=>l.status==='Booked').length,follow=state.leads.filter(isLeadDue).length,newCount=state.leads.filter(l=>l.status==='New').length,conversion=state.leads.length?Math.round(booked/state.leads.length*100):0;return `${heading('Know every customer','Leads & customers','A simple pipeline for enquiries, follow-ups, and bookings.','<button class="ghost-button" id="exportLeads">Export CSV</button><label class="ghost-button file-button" for="importLeads">Import CSV</label><input id="importLeads" type="file" accept=".csv,text/csv" hidden><button class="primary-button" id="addLead">+ Add lead</button>')}<div class="grid stats-grid">${stat('Follow-ups due',String(follow),follow?'Needs attention':'Nothing overdue','◷')}${stat('New enquiries',String(newCount),'Current pipeline','♙')}${stat('Bookings won',String(booked),`${conversion}% conversion`,'✓')}${stat('Total contacts',String(state.leads.length),'Saved locally','♙')}</div><section class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Customer</th><th>Contact</th><th>Source</th><th>Interested in</th><th>Next follow-up</th><th>Status</th><th>Action</th></tr></thead><tbody>${state.leads.length?state.leads.map((l,i)=>`<tr title="${escapeHtml(l.notes||'')}"><td><b>${escapeHtml(l.name)}</b><br><small class="muted">${escapeHtml(l.date||'')}</small></td><td>${escapeHtml(l.phone||'—')}</td><td>${escapeHtml(l.source)}</td><td>${escapeHtml(l.service)}</td><td>${l.followUp?`<span class="pill ${isLeadDue(l)?'orange':'green'}">${escapeHtml(l.followUp)}${isLeadDue(l)?' · due':''}</span>`:'<span class="muted">Not set</span>'}</td><td><select data-lead-status="${i}"><option ${l.status==='New'?'selected':''}>New</option><option ${l.status==='Follow-up'?'selected':''}>Follow-up</option><option ${l.status==='Booked'?'selected':''}>Booked</option><option ${l.status==='Lost'?'selected':''}>Lost</option></select></td><td><button class="text-button" data-edit-lead="${i}">Edit</button> <button class="text-button" data-delete-lead="${i}">Delete</button></td></tr>`).join(''):'<tr><td colspan="7">No leads yet.</td></tr>'}</tbody></table></div></section>`}
function appointments(){let active=state.appointments.filter(a=>a.status!=='Cancelled'),value=active.reduce((sum,a)=>sum+(Number(a.value)||0),0);return `${heading('Keep the day flowing','Appointments','Manage upcoming customer visits and expected booking value.','<button class="ghost-button" id="exportCalendar">Export calendar</button><button class="ghost-button" id="exportAppointments">Export CSV</button><button class="primary-button" data-action="appointment">+ New appointment</button>')}<div class="grid stats-grid">${stat('Active bookings',String(active.length),'Confirmed and pending','◫')}${stat('Confirmed',String(active.filter(a=>a.status==='Confirmed').length),'Ready to serve','✓')}${stat('Pending',String(active.filter(a=>a.status==='Pending').length),'Needs confirmation','◷')}${stat('Expected value',`₹${value.toLocaleString('en-IN')}`,'Active appointments','₹')}</div><section class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Date & time</th><th>Customer</th><th>Service</th><th>Staff</th><th>Value</th><th>Status</th><th>Action</th></tr></thead><tbody>${state.appointments.length?state.appointments.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(a=>{let i=state.appointments.indexOf(a);return `<tr><td>${escapeHtml(new Date(a.date).toLocaleString())}</td><td><b>${escapeHtml(a.customer)}</b></td><td>${escapeHtml(a.service)}</td><td>${escapeHtml(a.staff||'Unassigned')}</td><td>₹${Number(a.value||0).toLocaleString('en-IN')}</td><td><select data-appointment-status="${i}"><option ${a.status==='Pending'?'selected':''}>Pending</option><option ${a.status==='Confirmed'?'selected':''}>Confirmed</option><option ${a.status==='Completed'?'selected':''}>Completed</option><option ${a.status==='Cancelled'?'selected':''}>Cancelled</option></select></td><td><button class="text-button" data-edit-appointment="${i}">Edit</button> <button class="text-button" data-delete-appointment="${i}">Delete</button></td></tr>`}).join(''):'<tr><td colspan="7">No appointments saved.</td></tr>'}</tbody></table></div></section>`}
function analytics(){const visits=state.forecastData?.visits||[720,810,870,940,1080,1284],months=state.forecastMonths||['Jan','Feb','Mar','Apr','May','Jun'],latest=visits.at(-1)||0,previous=visits.at(-2)||latest,growth=previous?Math.round((latest-previous)/previous*100):0,bookings=state.appointments.filter(a=>a.status!=='Cancelled'),revenue=bookings.reduce((sum,a)=>sum+(Number(a.value)||0),0),chart=visits.slice(-7),max=Math.max(...chart,1),labels=months.slice(-chart.length);return `${heading('See what is working','Analytics overview','Live workspace metrics plus imported historical performance.','<button class="ghost-button" data-route="predictions">Import historical data</button><button class="ghost-button" data-action="placeholder">Connect Google Analytics</button>')}<div class="grid stats-grid">${stat('Website visits',latest.toLocaleString('en-IN'),state.forecastData?`${growth>=0?'↑':'↓'} ${Math.abs(growth)}% vs previous period`:'Demo history · import CSV','↗')}${stat('CRM leads',String(state.leads.length),'Current workspace total','♙')}${stat('Active bookings',String(bookings.length),'Confirmed and pending','✓')}${stat('Booking value',`₹${revenue.toLocaleString('en-IN')}`,'From active appointments','₹')}</div><div class="grid dashboard-grid"><section class="card"><div class="card-header"><div><h2 class="card-title">Website visit trend</h2><p class="card-subtitle">${state.forecastData?'Imported historical data':'Studio Salvadore demo history'}</p></div><span class="pill ${growth>=0?'green':'orange'}">${growth>=0?'+':''}${growth}%</span></div><div class="bar-chart">${chart.map(value=>`<div class="bar-group"><span class="bar orange" style="width:100%;height:${Math.max(5,Math.round(value/max*100))}%" title="${value.toLocaleString('en-IN')} visits"></span></div>`).join('')}</div><div class="chart-labels">${labels.map(x=>`<span>${escapeHtml(x)}</span>`).join('')}</div></section><aside class="card"><h2 class="card-title">Data sources</h2><p class="card-subtitle">Current measurement readiness</p>${[['↗','Historical CSV',state.forecastData?`${visits.length} periods imported`:'Demo data'],['♙','CRM',`${state.leads.length} local leads`],['◫','Appointments',`${state.appointments.length} local records`],['G','Google Analytics 4','Not connected']].map((x,i)=>`<div class="integration"><span class="integration-logo">${x[0]}</span><div><b>${x[1]}</b><p>${x[2]}</p></div>${i===3?'<button class="text-button" data-action="placeholder">Set up</button>':`<span class="pill ${i&&'green'}">Active</span>`}</div>`).join('')}</aside></div>`}
function predictions(){return `${heading('Plan with confidence','Charts & predictions','Explore likely leads and revenue from your current marketing trend. Forecasts are directional, not guarantees.','<button class="ghost-button" id="exportForecast">Export forecast</button>')}
<section class="card data-import"><div><h2 class="card-title">Historical data</h2><p class="card-subtitle" id="dataSourceLabel">Using Studio Salvadore demo data · import at least 4 monthly rows for your own forecast</p></div><div class="data-import-actions"><button class="text-button" id="downloadTemplate">Download template</button><label class="ghost-button file-button" for="forecastFile">Import CSV</label><input id="forecastFile" type="file" accept=".csv,text/csv" hidden></div></section>
<section class="card forecast-controls" aria-label="Forecast controls"><div class="field"><label for="forecastPeriod">Forecast period</label><select id="forecastPeriod"><option value="3">Next 3 months</option><option value="6" selected>Next 6 months</option><option value="12">Next 12 months</option></select></div><div class="field"><label for="forecastMetric">Primary metric</label><select id="forecastMetric"><option value="leads">Leads</option><option value="revenue">Revenue</option><option value="visits">Website visits</option></select></div><div class="range-field"><label for="budgetLift">Monthly marketing budget <strong id="budgetLiftValue">+20%</strong></label><input type="range" id="budgetLift" min="-20" max="100" step="5" value="20"></div><div class="range-field"><label for="conversionLift">Conversion improvement <strong id="conversionLiftValue">+5%</strong></label><input type="range" id="conversionLift" min="0" max="30" step="1" value="5"></div></section>
<section class="card combined-analysis"><div class="card-header"><div><h2 class="card-title">Combined analysis engine</h2><p class="card-subtitle">Technical signals 55% · business fundamentals 45%</p></div><span class="pill green" id="combinedSignal">Calculating</span></div><div class="analysis-layout"><div class="analysis-score"><div class="score-ring" id="technicalRing" style="--score:0"><strong id="technicalScore">—</strong></div><div><b>Technical analysis</b><p class="card-subtitle">Trend · momentum · volatility · consistency</p><div class="signal-list"><span>Trend <b id="trendSignal">—</b></span><span>Momentum <b id="momentumSignal">—</b></span><span>Risk <b id="volatilitySignal">—</b></span></div></div></div><div class="fundamentals"><div class="fundamental-head"><div><b>Fundamental analysis</b><p class="card-subtitle">Current business quality and demand signals</p></div><strong id="fundamentalScore">—</strong></div><div class="fundamental-inputs"><div class="field"><label for="conversionRate">Lead conversion %</label><input id="conversionRate" type="number" min="0" max="100" value="58"></div><div class="field"><label for="averageValue">Average booking ₹</label><input id="averageValue" type="number" min="0" value="2700"></div><div class="field"><label for="reviewRating">Google rating</label><input id="reviewRating" type="number" min="1" max="5" step="0.1" value="4.6"></div><div class="field"><label for="seoHealth">SEO health /100</label><input id="seoHealth" type="number" min="0" max="100" value="74"></div></div></div></div><div class="analysis-verdict" id="analysisVerdict">Evaluating signals…</div></section>
<div class="grid stats-grid forecast-stats"><div class="stat-card"><div class="stat-top"><span>Predicted leads</span><span class="stat-icon">♙</span></div><div class="stat-value" id="predictedLeads">—</div><div class="trend" id="leadsDelta">—</div></div><div class="stat-card"><div class="stat-top"><span>Predicted revenue</span><span class="stat-icon">₹</span></div><div class="stat-value" id="predictedRevenue">—</div><div class="trend" id="revenueDelta">—</div></div><div class="stat-card"><div class="stat-top"><span>Expected bookings</span><span class="stat-icon">✓</span></div><div class="stat-value" id="predictedBookings">—</div><div class="trend neutral">Based on current close rate</div></div><div class="stat-card"><div class="stat-top"><span>Confidence range</span><span class="stat-icon">±</span></div><div class="stat-value">Medium</div><div class="trend neutral">Demo historical dataset</div></div></div>
<div class="grid prediction-grid"><section class="card"><div class="card-header"><div><h2 class="card-title" id="forecastChartTitle">Lead forecast</h2><p class="card-subtitle">Actual history, baseline, and adjusted scenario</p></div><div class="chart-legend"><span><i class="legend-dot actual"></i>Actual</span><span><i class="legend-dot baseline"></i>Baseline</span><span><i class="legend-dot scenario"></i>Your scenario</span></div></div><div class="svg-chart" id="forecastChart" role="img" aria-label="Historical and predicted marketing performance line chart"></div></section><section class="card"><div class="card-header"><div><h2 class="card-title">Channel contribution</h2><p class="card-subtitle">Predicted lead share next period</p></div></div><div id="channelChart" class="channel-chart" role="img" aria-label="Predicted leads by channel"></div></section></div>
<section class="card" style="margin-top:18px"><div class="card-header"><div><h2 class="card-title">Prediction assumptions</h2><p class="card-subtitle">Transparent rules behind this MVP forecast</p></div></div><div class="assumption-grid"><div><b>Recent trend</b><p>Weighted growth from the latest six months.</p></div><div><b>Budget response</b><p>Each 10% budget change influences reach by roughly 4%.</p></div><div><b>Conversion response</b><p>The conversion slider applies directly to predicted enquiries.</p></div><div><b>Seasonality</b><p>Salon demand lifts around festive and wedding periods.</p></div></div></section>`}
function credits(){let used=state.usage.reduce((sum,row)=>sum+(Number(row.credits)||0),0),limit=100,percent=Math.min(100,Math.round(used/limit*100));return `${heading('Stay in control','Credits & API usage','See how automation and AI usage affect your budget.')}<div class="grid dashboard-grid"><section class="credit-box"><div class="eyebrow">Local allowance</div><div style="font:800 38px Manrope;margin-top:8px">${used} <span style="font-size:16px;color:#aaa">/ ${limit}</span></div><p style="color:#aaa">Local workflow credits</p><div class="progress"><span style="width:${percent}%"></span></div><small>Browser-local tracking · estimated API cost ₹0</small></section><section class="card"><h2 class="card-title">Free-first guardrails</h2><ul class="checklist"><li><span class="check-dot">✓</span>Local generation enabled</li><li><span class="check-dot">✓</span>Usage limit shown at 100</li><li><span class="check-dot">✓</span>No paid API connected</li></ul></section></div><section class="card" style="margin-top:18px"><div class="card-header"><div><h2 class="card-title">Usage history</h2><p class="card-subtitle">Actions recorded in this browser</p></div><button class="text-button" id="clearUsage">Clear history</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Date</th><th>Action</th><th>Provider</th><th>Credits</th></tr></thead><tbody>${state.usage.length?state.usage.map(row=>`<tr><td>${escapeHtml(row.date)}</td><td>${escapeHtml(row.action)}</td><td>Local engine</td><td>${row.credits}</td></tr>`).join(''):'<tr><td colspan="4">No tracked actions yet.</td></tr>'}</tbody></table></div></section>`}
function settings(){let b=state.business,e=escapeHtml;return `${heading('Your business foundation','Business settings','Keep this aligned with your website and Google Business Profile.','<button class="ghost-button" id="exportBackup">Export backup</button><label class="ghost-button file-button" for="importBackup">Import backup</label><input id="importBackup" type="file" accept="application/json,.json" hidden>')}<div class="settings-layout"><aside class="card settings-nav"><button class="active">Business profile</button><button>Brand voice</button><button>Locations</button><button>Integrations</button><button>Team</button></aside><section class="card"><div class="card-header"><div><h2 class="card-title">Business profile</h2><p class="card-subtitle">Used across content, local SEO, and reporting. Your workspace is stored on this device; export a backup before clearing browser data.</p></div></div><form id="settingsForm" class="form-grid"><div class="field full"><label>Business name</label><input name="name" value="${e(b.name)}"></div><div class="field"><label>Category</label><input name="category" value="${e(b.category)}"></div><div class="field"><label>Phone</label><input name="phone" value="${e(b.phone)}"></div><div class="field"><label>Email</label><input name="email" value="${e(b.email)}"></div><div class="field"><label>Website</label><input name="website" value="${e(b.website)}"></div><div class="field"><label>Google review URL</label><input name="reviewUrl" value="${e(b.reviewUrl)}" placeholder="https://g.page/r/…/review"></div><div class="field full"><label>Address / service area</label><input name="address" value="${e(b.address)}"></div><div class="field full"><label>Opening hours</label><input name="hours" value="${e(b.hours)}"></div><div class="field full"><label>Short description</label><textarea name="description">${e(b.description)}</textarea></div><div class="field full"><label>Brand voice</label><input name="tone" value="${e(b.tone)}"></div><div class="field full"><div><button class="primary-button">Save changes</button></div></div></form></section></div>`}
const views={dashboard,planner,scheduler,generator,seo,local:localSeo,analytics,predictions,crm,appointments,credits,settings};
function route(name){name=views[name]?name:'dashboard';location.hash=name;renderNav();updateShellStatus();$('#app').innerHTML=views[name]();$('#pageCrumb').textContent=titles[name];$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.route===name));$('#sidebar').classList.remove('open');$('#app').focus();bindPage();}
function toast(msg){let el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2500)}
function modal(title,body,submit='Save'){let d=$('#modal');$('#modalContent').innerHTML=`<div class="modal-head"><h2>${title}</h2><button class="icon-button" value="cancel">×</button></div>${body}<div class="modal-actions"><button class="ghost-button" value="cancel">Cancel</button><button class="primary-button" value="default">${submit}</button></div>`;d.showModal();return d}
function notificationItems(){const due=state.leads.filter(isLeadDue).length,pending=state.appointments.filter(a=>a.status==='Pending').length,drafts=state.posts.filter(p=>p.status==='Draft'||p.date==='Unscheduled').length,local=state.localSeoChecks.filter(x=>!x).length;return [{route:'crm',icon:'♙',title:`${due} follow-up${due===1?'':'s'} due`,detail:'Review customers who need attention',count:due},{route:'appointments',icon:'◫',title:`${pending} appointment${pending===1?'':'s'} pending`,detail:'Confirm or reschedule bookings',count:pending},{route:'planner',icon:'▦',title:`${drafts} content draft${drafts===1?'':'s'}`,detail:'Finish and schedule planned content',count:drafts},{route:'local',icon:'⌖',title:`${local} local SEO task${local===1?'':'s'} open`,detail:'Improve Google Business readiness',count:local}].filter(item=>item.count)}
function updateShellStatus(){const items=notificationItems(),button=$('#notificationButton'),dot=button?.querySelector('i'),name=state.business.name||'MarketingMind Workspace',category=state.business.category||'Local business',initials=name.split(/\s+/).filter(Boolean).slice(0,2).map(word=>word[0]).join('').toUpperCase();if(button){button.title=items.length?`${items.length} action groups need attention`:'No pending notifications';if(dot)dot.hidden=!items.length}if($('#workspaceName'))$('#workspaceName').textContent=name;if($('#workspaceCategory'))$('#workspaceCategory').textContent=category;if($('#workspaceAvatar'))$('#workspaceAvatar').textContent=initials||'M';document.title=`MarketingMind AI — ${name}`}
function notificationModal(){const items=notificationItems(),body=items.length?`<div class="notification-list">${items.map(item=>`<button type="button" class="notification-item" data-notification-route="${item.route}"><span>${item.icon}</span><div><b>${item.title}</b><small>${item.detail}</small></div><strong>→</strong></button>`).join('')}</div>`:'<div class="empty-state"><span>✓</span><h3>You are all caught up</h3><p>No urgent workspace actions right now.</p></div>',d=modal('Action centre',body,'Close');$$('[data-notification-route]').forEach(button=>button.onclick=()=>{d.close();route(button.dataset.notificationRoute)});d.onsubmit=event=>{event.preventDefault();d.close()}}
function localSchema(){const business=state.business,schema={'@context':'https://schema.org','@type':business.category?.toLowerCase().includes('salon')?'BeautySalon':'LocalBusiness',name:business.name,description:business.description,telephone:business.phone,email:business.email,url:business.website,address:{'@type':'PostalAddress',streetAddress:business.address,addressCountry:'IN'},openingHours:business.hours};Object.keys(schema).forEach(key=>{if(schema[key]==='')delete schema[key]});return schema}
function schemaModal(){const json=JSON.stringify(localSchema(),null,2),d=modal('LocalBusiness JSON-LD',`<p class="muted">Review the business details, then add this JSON-LD inside your website’s &lt;head&gt;. Validate it before production use.</p><div class="field"><label>Generated schema</label><textarea id="schemaOutput" style="min-height:310px;font-family:monospace">${escapeHtml(json)}</textarea></div><div style="margin-top:12px"><button type="button" class="ghost-button" id="copySchema">Copy schema</button></div>`,'Download JSON');$('#copySchema').onclick=()=>navigator.clipboard?.writeText($('#schemaOutput').value).then(()=>toast('Schema copied'));d.onsubmit=event=>{event.preventDefault();downloadText($('#schemaOutput').value,'localbusiness-schema.json');d.close();toast('Schema downloaded')}}
function exportLocalSeoReport(){const items=['Business name matches your storefront','Primary category selected','Phone and opening hours added','Website link uses tracking tags','Services and prices completed','Business description added','20+ authentic customer reviews','Weekly photo or update published'],rows=[['MarketingMind Local SEO Report',''],['Generated',new Date().toISOString()],['Business',state.business.name],['Category',state.business.category],['Address',state.business.address],['Phone',state.business.phone],['Website',state.business.website],['Opening hours',state.business.hours],[],['Checklist item','Status'],...items.map((item,index)=>[item,state.localSeoChecks[index]?'Complete':'Open'])];downloadText(rows.map(row=>row.map(csvCell).join(',')).join('\n'),'marketingmind-local-seo-report.csv');toast('Local SEO report exported')}
function seoAuditModal(){let d=modal('Analyze page HTML',`<p class="muted">Open the page source of a website, copy the complete HTML, and paste it below. Analysis stays in this browser.</p><div class="field"><label>Page HTML</label><textarea id="auditHtml" style="min-height:280px;font-family:monospace" placeholder="<!doctype html>…" required></textarea></div>`,'Analyze SEO');d.onsubmit=event=>{event.preventDefault();const source=$('#auditHtml').value.trim();if(!source){toast('Paste page HTML first');return}const doc=new DOMParser().parseFromString(source,'text/html'),title=doc.querySelector('title')?.textContent.trim()||'',description=doc.querySelector('meta[name="description"]')?.content.trim()||'',h1=doc.querySelectorAll('h1').length,images=[...doc.querySelectorAll('img')],missingAlt=images.filter(image=>!image.hasAttribute('alt')||!image.getAttribute('alt').trim()).length,checks=[['Title tag',title.length>=20&&title.length<=65,title?`${title.length} characters`:'Missing'],['Meta description',description.length>=70&&description.length<=170,description?`${description.length} characters`:'Missing'],['Single H1',h1===1,`${h1} found`],['Mobile viewport',!!doc.querySelector('meta[name="viewport"]'),doc.querySelector('meta[name="viewport"]')?'Present':'Missing'],['Canonical URL',!!doc.querySelector('link[rel="canonical"]'),doc.querySelector('link[rel="canonical"]')?.href||'Missing'],['Image ALT text',missingAlt===0,images.length?`${missingAlt} of ${images.length} missing`:'No images found'],['JSON-LD schema',!!doc.querySelector('script[type="application/ld+json"]'),doc.querySelector('script[type="application/ld+json"]')?'Present':'Missing']],passed=checks.filter(check=>check[1]).length,score=Math.round(passed/checks.length*100);state.seoAudit={score,checks,date:new Date().toISOString()};save();logUsage('Local HTML SEO audit',1);d.close();let result=modal(`SEO audit · ${score}/100`,`<div class="score-row" style="margin-bottom:16px"><div class="score-ring" style="--score:${score}"><strong>${score}</strong></div><div><b>${passed} of ${checks.length} checks passed</b><p class="card-subtitle">Saved locally · review content quality manually.</p></div></div>${checks.map(([name,ok,detail])=>`<div class="audit-row"><span class="audit-state ${ok?'':'warn'}">${ok?'✓':'!'}</span><div><b>${name}</b><p>${escapeHtml(detail)}</p></div><span class="pill ${ok?'green':'orange'}">${ok?'Passed':'Improve'}</span></div>`).join('')}`,'Close');result.onsubmit=e=>{e.preventDefault();result.close();route('seo')}}}
function utmModal(){let d=modal('Build a campaign URL',`<div class="form-grid"><div class="field full"><label>Landing page URL</label><input id="utmUrl" type="url" value="${escapeHtml(state.business.website||'')}" placeholder="https://example.com/offer" required></div><div class="field"><label>Campaign source</label><input id="utmSource" value="instagram" placeholder="instagram, google, newsletter" required></div><div class="field"><label>Campaign medium</label><input id="utmMedium" value="social" placeholder="social, cpc, email" required></div><div class="field full"><label>Campaign name</label><input id="utmCampaign" placeholder="monsoon-hair-spa" required></div><div class="field"><label>Content label</label><input id="utmContent" placeholder="reel-a (optional)"></div><div class="field"><label>Search term</label><input id="utmTerm" placeholder="hair spa (optional)"></div></div>`,'Generate link');d.onsubmit=event=>{event.preventDefault();try{const url=new URL($('#utmUrl').value),set=(key,value)=>{if(value.trim())url.searchParams.set(key,value.trim().toLowerCase().replace(/\s+/g,'-'))};set('utm_source',$('#utmSource').value);set('utm_medium',$('#utmMedium').value);set('utm_campaign',$('#utmCampaign').value);set('utm_content',$('#utmContent').value);set('utm_term',$('#utmTerm').value);d.close();let result=modal('Campaign URL ready',`<div class="field"><label>Tracked URL</label><textarea id="utmOutput" style="min-height:130px">${escapeHtml(url.toString())}</textarea></div><p class="muted">Use the same naming convention across campaigns so GA4 reports stay clean.</p>`,'Copy link');result.onsubmit=e=>{e.preventDefault();navigator.clipboard?.writeText($('#utmOutput').value);logUsage('UTM campaign link',1);result.close();toast('Campaign URL copied')}}catch{toast('Enter a valid landing page URL')}}}
function contentModal(){let d=modal('Create content',`<div class="form-grid"><div class="field full"><label>Post idea</label><input id="newTitle" placeholder="What do you want to share?"></div><div class="field"><label>Channel</label><select id="newChannel"><option>Instagram</option><option>Facebook</option><option>Google Business</option></select></div><div class="field"><label>Publish date</label><input id="newDate" type="datetime-local"></div></div>`,'Add to planner');d.onsubmit=e=>{e.preventDefault();let title=$('#newTitle').value.trim();if(!title)return;state.posts.unshift({title,channel:$('#newChannel').value,status:'Draft',date:$('#newDate').value?new Date($('#newDate').value).toLocaleString():'Unscheduled',theme:'alt'});save();d.close();toast('Draft added to your planner');if(location.hash==='#planner')route('planner')};}
function editPostModal(index){let post=state.posts[index];if(!post)return;let d=modal('Edit content',`<div class="form-grid"><div class="field full"><label>Title</label><input id="editPostTitle" value="${escapeHtml(post.title)}" required></div><div class="field"><label>Channel</label><select id="editPostChannel">${['Instagram','Facebook','Google Business','Blog'].map(x=>`<option ${post.channel===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Status</label><select id="editPostStatus">${['Draft','Ready','Scheduled'].map(x=>`<option ${post.status===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field full"><label>Publish date and time</label><input id="editPostDate" type="datetime-local"></div><div class="field full"><label>Copy</label><textarea id="editPostCopy">${escapeHtml(post.copy||'')}</textarea></div></div>`,'Save content');d.onsubmit=e=>{e.preventDefault();let date=$('#editPostDate').value;state.posts[index]={...post,title:$('#editPostTitle').value.trim(),channel:$('#editPostChannel').value,status:$('#editPostStatus').value,date:date?new Date(date).toLocaleString():post.date,copy:$('#editPostCopy').value};save();d.close();route(location.hash.slice(1)||'planner');toast('Content updated')}}
function appointmentModal(){let d=modal('New appointment',`<div class="form-grid"><div class="field"><label>Customer</label><input id="appointmentCustomer" required></div><div class="field"><label>Service</label><input id="appointmentService" required></div><div class="field"><label>Team member</label><input id="appointmentStaff" placeholder="Optional"></div><div class="field"><label>Date and time</label><input id="appointmentDate" type="datetime-local" required></div><div class="field"><label>Estimated value ₹</label><input id="appointmentValue" type="number" min="0" value="0"></div><div class="field"><label>Status</label><select id="appointmentStatus"><option>Pending</option><option>Confirmed</option></select></div><div class="field full"><label><input id="appointmentLead" type="checkbox" checked> Add customer to CRM if not already present</label></div></div>`,'Save appointment');d.onsubmit=e=>{e.preventDefault();let customer=$('#appointmentCustomer').value.trim(),service=$('#appointmentService').value.trim(),staff=$('#appointmentStaff').value.trim(),date=$('#appointmentDate').value;if(hasAppointmentConflict(date,staff)&&!confirm('This team member already has a booking at this time. Save anyway?'))return;state.appointments.push({customer,service,staff,date,value:Math.max(0,Number($('#appointmentValue').value)||0),status:$('#appointmentStatus').value});if($('#appointmentLead').checked&&!state.leads.some(l=>l.name.toLowerCase()===customer.toLowerCase()))state.leads.unshift({name:customer,source:'Appointment',service,status:'Booked',date:'Today'});save();d.close();route('appointments');toast('Appointment saved')}}
function hasAppointmentConflict(date,staff,except=-1){if(!date||!staff)return false;return state.appointments.some((a,i)=>i!==except&&a.status!=='Cancelled'&&a.date===date&&(a.staff||'').toLowerCase()===staff.toLowerCase())}
function editAppointmentModal(index){const item=state.appointments[index];if(!item)return;let d=modal('Edit appointment',`<div class="form-grid"><div class="field"><label>Customer</label><input id="editAppointmentCustomer" value="${escapeHtml(item.customer)}" required></div><div class="field"><label>Service</label><input id="editAppointmentService" value="${escapeHtml(item.service)}" required></div><div class="field"><label>Team member</label><input id="editAppointmentStaff" value="${escapeHtml(item.staff||'')}"></div><div class="field"><label>Date and time</label><input id="editAppointmentDate" type="datetime-local" value="${escapeHtml(item.date)}" required></div><div class="field"><label>Estimated value ₹</label><input id="editAppointmentValue" type="number" min="0" value="${Number(item.value)||0}"></div><div class="field"><label>Status</label><select id="editAppointmentStatus">${['Pending','Confirmed','Completed','Cancelled'].map(x=>`<option ${item.status===x?'selected':''}>${x}</option>`).join('')}</select></div></div>`,'Save changes');d.onsubmit=event=>{event.preventDefault();const date=$('#editAppointmentDate').value,staff=$('#editAppointmentStaff').value.trim();if(hasAppointmentConflict(date,staff,index)&&!confirm('This team member already has a booking at this time. Save anyway?'))return;state.appointments[index]={customer:$('#editAppointmentCustomer').value.trim(),service:$('#editAppointmentService').value.trim(),staff,date,value:Math.max(0,Number($('#editAppointmentValue').value)||0),status:$('#editAppointmentStatus').value};save();d.close();route('appointments');toast('Appointment updated')}}
function appointmentReminderModal(index){const item=state.appointments[index];if(!item)return;const when=new Date(item.date).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}),message=`Hello ${item.customer}, this is a reminder for your ${item.service} appointment at ${state.business.name} on ${when}${item.staff?` with ${item.staff}`:''}. ${state.business.address?`Location: ${state.business.address}. `:''}Please reply if you need to reschedule. We look forward to seeing you!`,d=modal('Appointment reminder',`<div class="field"><label>Customer message</label><textarea id="appointmentReminder" style="min-height:210px">${escapeHtml(message)}</textarea></div><p class="muted">Review the date and customer details before sending through your preferred messaging app.</p>`,'Copy reminder');d.onsubmit=event=>{event.preventDefault();navigator.clipboard?.writeText($('#appointmentReminder').value);logUsage('Appointment reminder',1);d.close();toast('Appointment reminder copied')}}
function isLeadDue(lead){if(!lead.followUp||['Booked','Lost'].includes(lead.status))return false;return lead.followUp<=new Date().toISOString().slice(0,10)}
function editLeadModal(index){const lead=state.leads[index];if(!lead)return;let d=modal('Edit lead',`<div class="form-grid"><div class="field"><label>Name</label><input id="editLeadName" value="${escapeHtml(lead.name)}" required></div><div class="field"><label>Phone</label><input id="editLeadPhone" type="tel" value="${escapeHtml(lead.phone||'')}"></div><div class="field"><label>Source</label><input id="editLeadSource" value="${escapeHtml(lead.source||'')}"></div><div class="field"><label>Next follow-up</label><input id="editLeadFollowUp" type="date" value="${escapeHtml(lead.followUp||'')}"></div><div class="field full"><label>Interested in</label><input id="editLeadService" value="${escapeHtml(lead.service||'')}"></div><div class="field full"><label>Notes</label><textarea id="editLeadNotes">${escapeHtml(lead.notes||'')}</textarea></div></div>`,'Save lead');d.onsubmit=event=>{event.preventDefault();state.leads[index]={...lead,name:$('#editLeadName').value.trim(),phone:$('#editLeadPhone').value.trim(),source:$('#editLeadSource').value.trim()||'Unknown',service:$('#editLeadService').value.trim()||'Not specified',followUp:$('#editLeadFollowUp').value,notes:$('#editLeadNotes').value.trim(),date:'Today'};save();d.close();route('crm');toast('Lead updated')}}
function leadFollowUpModal(index){const lead=state.leads[index];if(!lead)return;const message=`Hello ${lead.name}, thank you for your interest in ${lead.service||'our services'} at ${state.business.name}. Our team would be happy to answer your questions and help you choose the right option. Would you like us to reserve a convenient appointment time for you?${state.business.phone?` You can also reach us at ${state.business.phone}.`:''}`,d=modal('Lead follow-up message',`<div class="field"><label>Customer message</label><textarea id="leadFollowUpMessage" style="min-height:220px">${escapeHtml(message)}</textarea></div><p class="muted">Review the message and contact only customers who have consented to receive follow-ups.</p>`,'Copy message');d.onsubmit=event=>{event.preventDefault();navigator.clipboard?.writeText($('#leadFollowUpMessage').value);lead.date='Today';if(lead.status==='New')lead.status='Follow-up';logUsage('CRM follow-up message',1);save();d.close();route('crm');toast('Follow-up message copied')}}
function reviewRequestModal(){let message=`Thank you for visiting ${state.business.name}. If you enjoyed your experience, would you share an honest Google review? Your feedback helps our local team grow. ${state.business.reviewUrl||'[Add your Google review URL in Business settings]'}`,d=modal('Google review request',`<div class="field"><label>Customer message</label><textarea id="reviewMessage" style="min-height:180px">${escapeHtml(message)}</textarea></div><p class="muted">Send only to genuine customers who have used your service. Do not offer incentives for reviews.</p>`,'Copy message');d.onsubmit=e=>{e.preventDefault();navigator.clipboard?.writeText($('#reviewMessage').value);logUsage('Google review request',1);d.close();toast('Review request copied')}}
const integrationGuides={
  supabase:{name:'Supabase cloud sync',variables:['SUPABASE_URL','SUPABASE_ANON_KEY'],note:'Create a free Supabase project, then copy the Project URL and public anon key. Never use the service-role key here.'},
  openai:{name:'OpenAI content generation',variables:['OPENAI_API_KEY','OPENAI_MODEL'],note:'Create an API key and save it only as a Cloudflare secret. OPENAI_MODEL is optional; the app has a safe default.'},
  google:{name:'Google Business OAuth',variables:['GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET'],note:'Create a Google Cloud OAuth client and add the production callback URL before connecting a Business Profile.'},
  ga4:{name:'Google Analytics 4',variables:['GA4_PROPERTY_ID'],note:'Use the numeric GA4 property ID. Read-only reporting permissions should be used for the first connection.'},
  meta:{name:'Meta publishing OAuth',variables:['META_APP_ID','META_APP_SECRET'],note:'Create a Meta app and request only the publishing permissions your business actually needs.'}
};
function integrationSetupModal(id){const guide=integrationGuides[id];if(!guide)return;const variables=guide.variables.join('\n'),d=modal(`Set up ${guide.name}`,`<div class="setup-steps"><div><span>1</span><p><b>Open Cloudflare Pages settings</b><br><small>Go to your MarketingMind project → Settings → Variables and Secrets.</small></p></div><div><span>2</span><p><b>Add the required names</b><br><small>Use Secret for private keys. Production and preview values can be managed separately.</small></p></div><div><span>3</span><p><b>Deploy and check again</b><br><small>After saving, redeploy once and return to Integration readiness.</small></p></div></div><div class="field"><label>Required variable names</label><textarea id="integrationVariables" readonly>${escapeHtml(variables)}</textarea></div><p class="integration-note">${escapeHtml(guide.note)}</p><a class="ghost-button setup-link" href="https://dash.cloudflare.com/" target="_blank" rel="noopener">Open Cloudflare dashboard ↗</a>`,'Copy variable names');d.onsubmit=event=>{event.preventDefault();navigator.clipboard?.writeText(variables);d.close();toast('Variable names copied — add your own secret values in Cloudflare')}}
function createLocalDraft(topic,type,goal,language,variant=0){
  const business=state.business.name,ctas={bookings:['Book your appointment today.','Reserve your preferred time now.','Message our team for a personalised consultation.'],offer:['Message us to claim the offer.','Book before the offer ends.','Ask our team for availability today.'],educate:['Save this tip and ask our team what suits you.','Share this with someone who needs it.','Book a consultation for personalised advice.'],awareness:['Follow us for more salon and self-care inspiration.','Discover more personalised care from our team.','Visit us and experience the difference.']},group=goal==='Get bookings'?'bookings':goal==='Promote an offer'?'offer':goal==='Educate customers'?'educate':'awareness',cta=ctas[group][variant%3];
  if(language==='Bengali')return [`${topic} নিয়ে ${business}-এর বিশেষ যত্ন।`,`আপনার ${topic} নিয়ে চিন্তা হচ্ছে? ${business}-এর টিম পাশে আছে।`,`নিজের যত্নে আজ একটু সময় দিন—${topic} নিয়ে ${business}-এর ব্যক্তিগত সেবা নিন।`][variant%3]+` আপনার চুল, ত্বক ও স্বস্তির প্রয়োজন বুঝে আমাদের টিম ব্যক্তিগতভাবে সেবা সাজায়। আজই যোগাযোগ করে আপনার সময় বুক করুন।\n\n#StudioSalvadore #KolkataSalon #SalonAndSpa`;
  if(language==='Hindi')return [`${topic} के लिए ${business} की खास देखभाल।`,`क्या आप ${topic} को लेकर परेशान हैं? ${business} की टीम आपकी मदद के लिए तैयार है।`,`अपने लिए थोड़ा समय निकालें—${topic} के लिए व्यक्तिगत देखभाल चुनें।`][variant%3]+` हमारी टीम आपकी ज़रूरत के अनुसार व्यक्तिगत सलाह और सेवा देती है। आज ही अपना अपॉइंटमेंट बुक करें।\n\n#StudioSalvadore #KolkataSalon #SalonAndSpa`;
  if(type==='Blog outline')return `Title: ${topic}\n\n1. Why this matters\n2. Common concerns and mistakes\n3. Professional care options\n4. At-home maintenance tips\n5. When to book a consultation\n\nConclusion: ${cta}`;
  const openers=type==='Facebook ad'?['Ready for a little transformation?','Your next confident look starts here.','Kolkata, it is time to treat yourself.']:type==='Google Business update'?['Now at Studio Salvadore:','A fresh reason to visit us this week:','New for our Kolkata community:']:['A little care can change the way your whole week feels. ✨','Your self-care reminder has arrived. ✨','Good hair and calm moments begin with thoughtful care. ✨'],opener=openers[variant%3];
  return `${opener}\n\n${topic}. At ${business}, our team combines thoughtful consultation with personalised salon and spa care, so every visit feels confidently yours. ${cta}\n\n#StudioSalvadore #KolkataSalon #SalonAndSpa`;
}
function renderServerDraft(draft,topic,type,goal,language,model){const out=$('#generatedOutput'),channel=type.startsWith('Instagram')?'Instagram':type.startsWith('Facebook')?'Facebook':type.startsWith('Google')?'Google Business':'Blog';out.style.display='block';out.innerHTML=`<div class="card-header"><div><h2 class="card-title">Server AI draft</h2><p class="card-subtitle">${escapeHtml(model||'OpenAI')} · review every claim before publishing</p></div><div><button class="ghost-button" id="copyServerDraft">Copy</button> <button class="primary-button" id="saveServerDraft">Save to planner</button></div></div><textarea id="serverDraftText" style="width:100%;min-height:210px;font-size:15px;line-height:1.7">${escapeHtml(draft)}</textarea><div class="content-meta" style="margin-top:12px"><span>${escapeHtml(type)} · ${escapeHtml(goal)} · ${escapeHtml(language)}</span><button class="text-button" id="scheduleServerDraft">Schedule instead →</button></div>`;$('#copyServerDraft').onclick=()=>navigator.clipboard?.writeText($('#serverDraftText').value).then(()=>toast('Server draft copied'));$('#saveServerDraft').onclick=()=>{state.posts.unshift({title:topic,copy:$('#serverDraftText').value,channel,status:'Draft',date:'Unscheduled',theme:'alt'});save();toast('Server draft saved to planner')};$('#scheduleServerDraft').onclick=()=>{let d=modal('Schedule server draft',`<div class="field"><label>Publish date and time</label><input id="serverDraftDate" type="datetime-local" required></div>`,'Schedule');d.onsubmit=e=>{e.preventDefault();state.posts.unshift({title:topic,copy:$('#serverDraftText').value,channel,status:'Scheduled',date:new Date($('#serverDraftDate').value).toLocaleString(),theme:'third'});save();d.close();toast('Server draft added to publishing queue')}}}
function bindPage(){
  if($('#settingsForm')){const form=$('#settingsForm'),field=name=>form.elements.namedItem(name);['name','category','phone','address','website'].forEach(name=>field(name)?.setAttribute('required',''));field('email')?.setAttribute('type','email');field('website')?.setAttribute('type','url');field('reviewUrl')?.setAttribute('type','url');field('phone')?.setAttribute('type','tel');form.insertAdjacentHTML('beforebegin','<div class="card" style="margin-bottom:18px;padding:15px"><div class="card-header" style="margin-bottom:10px"><div><b>Profile completeness</b><p class="card-subtitle">Complete business details improve content and local SEO output.</p></div><strong id="profileCompleteness">0%</strong></div><div class="progress"><span id="profileCompletenessBar" style="width:0%"></span></div></div>');form.insertAdjacentHTML('afterend','<div class="card" style="margin-top:18px"><div class="card-header"><div><h2 class="card-title">Integration readiness</h2><p class="card-subtitle">Secure server environment check—secret values are never returned.</p></div><span class="pill" id="integrationSummary">Checking…</span></div><div id="integrationStatus"><p class="muted">Contacting the Cloudflare backend…</p></div></div>');const updateCompleteness=()=>{const names=['name','category','phone','email','website','reviewUrl','address','hours','description','tone'],complete=names.filter(name=>String(field(name)?.value||'').trim()).length,score=Math.round(complete/names.length*100);$('#profileCompleteness').textContent=`${score}%`;$('#profileCompletenessBar').style.width=`${score}%`};form.addEventListener('input',updateCompleteness);updateCompleteness();fetch('/api/integrations',{cache:'no-store'}).then(response=>response.ok?response.json():Promise.reject()).then(data=>{$('#integrationSummary').textContent=`${data.configured}/${data.total} configured`;$('#integrationSummary').className=`pill ${data.configured===data.total?'green':'orange'}`;$('#integrationStatus').innerHTML=data.integrations.map(item=>`<div class="integration"><span class="integration-logo">${item.configured?'✓':'○'}</span><div><b>${escapeHtml(item.name)}</b><p>${item.configured?'Server environment ready':'Environment variables not configured'}</p></div><span class="pill ${item.configured?'green':'orange'}">${item.configured?'Ready':'Setup needed'}</span></div>`).join('')}).catch(()=>{$('#integrationSummary').textContent='Unavailable';$('#integrationStatus').innerHTML='<p class="muted">Backend status could not be loaded. Local MVP features still work.</p>'})}
  if($('#clearUsage')&&!$('#exportUsage'))$('#clearUsage').insertAdjacentHTML('beforebegin','<button class="text-button" id="exportUsage">Export CSV</button> ');
  if($('#integrationStatus')){const panel=$('#integrationStatus'),enhanceIntegrations=()=>{$$('.integration',panel).forEach((row,index)=>{const id=Object.keys(integrationGuides)[index];if(!id||row.querySelector('[data-integration-guide]'))return;const status=row.querySelector('.pill');if(status?.textContent==='Setup needed'){const button=document.createElement('button');button.className='ghost-button integration-guide';button.type='button';button.dataset.integrationGuide=id;button.textContent='Setup guide';button.onclick=()=>integrationSetupModal(id);row.append(button)}})};new MutationObserver(enhanceIntegrations).observe(panel,{childList:true,subtree:true});enhanceIntegrations();const card=panel.closest('.card'),header=card?.querySelector('.card-header');if(header&&!$('#recheckIntegrations')){const recheck=document.createElement('button');recheck.id='recheckIntegrations';recheck.className='text-button';recheck.type='button';recheck.textContent='Check again';recheck.onclick=()=>route('settings');header.append(recheck)}const settingsButtons=$$('.settings-nav button');settingsButtons.forEach(button=>button.onclick=()=>{settingsButtons.forEach(item=>item.classList.remove('active'));button.classList.add('active');const label=button.textContent.trim();if(label==='Integrations')card?.scrollIntoView({behavior:'smooth',block:'start'});else if(label==='Brand voice')document.querySelector('[name="tone"]')?.focus();else if(label==='Locations')document.querySelector('[name="address"]')?.focus();else if(label==='Business profile')$('#settingsForm')?.scrollIntoView({behavior:'smooth',block:'start'});else toast('Team access is planned for the cloud workspace')})}
  if(location.hash==='#local'){const actions=$('.heading-actions');if(actions){const report=document.createElement('button');report.className='ghost-button';report.textContent='Export report';report.type='button';report.onclick=exportLocalSeoReport;actions.append(report);const button=document.createElement('button');button.className='primary-button';button.textContent='Generate schema';button.type='button';button.onclick=schemaModal;actions.append(button)}}
  if(location.hash==='#analytics'){const actions=$('.heading-actions');if(actions){const button=document.createElement('button');button.className='primary-button';button.textContent='Build UTM link';button.type='button';button.onclick=utmModal;actions.append(button)}}
  if($('#plannerCards')){const filterPlanner=()=>{const status=$('#plannerStatus').value,channel=$('#plannerChannel').value;let visible=0;$$('[data-plan-card]').forEach(card=>{const show=(!status||card.dataset.status===status)&&(!channel||card.dataset.channel===channel);card.hidden=!show;if(show)visible++});$('#plannerCount').textContent=`${visible} of ${state.posts.length} content items`};$('#plannerStatus').onchange=filterPlanner;$('#plannerChannel').onchange=filterPlanner}
  if($('#scheduleStatus')){const filterSchedule=()=>{const status=$('#scheduleStatus').value,channel=$('#scheduleChannel').value;let visible=0;$$('[data-schedule-row]').forEach(row=>{const show=(!status||row.dataset.status===status)&&(!channel||row.dataset.channel===channel);row.hidden=!show;if(show)visible++});$('#scheduleCount').textContent=`${visible} of ${state.posts.length} publishing items shown`};$('#scheduleStatus').onchange=filterSchedule;$('#scheduleChannel').onchange=filterSchedule}
  if(location.hash==='#crm'&&state.leads.length){const table=$('.data-table'),wrap=table?.closest('.table-wrap');wrap?.insertAdjacentHTML('beforebegin',`<div class="planner-toolbar"><div class="planner-filters"><label>Search <input id="crmSearch" type="search" placeholder="Name, phone, service…"></label><label>Status <select id="crmStatus"><option value="">All statuses</option><option>New</option><option>Follow-up</option><option>Booked</option><option>Lost</option></select></label></div><small class="muted" id="crmCount">${state.leads.length} leads</small></div>`);const rows=$$('tbody tr',table);rows.forEach((row,index)=>{const lead=state.leads[index];row.dataset.crmRow='';row.dataset.status=lead.status;row.dataset.search=[lead.name,lead.phone,lead.source,lead.service,lead.notes].join(' ').toLowerCase()});const filterCrm=()=>{const term=$('#crmSearch').value.trim().toLowerCase(),status=$('#crmStatus').value;let visible=0;rows.forEach(row=>{const show=(!term||row.dataset.search.includes(term))&&(!status||row.dataset.status===status);row.hidden=!show;if(show)visible++});$('#crmCount').textContent=`${visible} of ${state.leads.length} leads shown`};$('#crmSearch').oninput=filterCrm;$('#crmStatus').onchange=filterCrm}
  if(location.hash==='#appointments'&&state.appointments.length){const table=$('.data-table'),wrap=table?.closest('.table-wrap'),sorted=state.appointments.slice().sort((a,b)=>a.date.localeCompare(b.date));wrap?.insertAdjacentHTML('beforebegin',`<div class="planner-toolbar"><div class="planner-filters"><label>Search <input id="appointmentSearch" type="search" placeholder="Customer, service, staff…"></label><label>Status <select id="appointmentFilterStatus"><option value="">All statuses</option><option>Pending</option><option>Confirmed</option><option>Completed</option><option>Cancelled</option></select></label></div><small class="muted" id="appointmentCount">${state.appointments.length} appointments</small></div>`);const rows=$$('tbody tr',table);rows.forEach((row,index)=>{const item=sorted[index];row.dataset.appointmentRow='';row.dataset.status=item.status;row.dataset.search=[item.customer,item.service,item.staff,item.date].join(' ').toLowerCase()});const filterAppointments=()=>{const term=$('#appointmentSearch').value.trim().toLowerCase(),status=$('#appointmentFilterStatus').value;let visible=0;rows.forEach(row=>{const show=(!term||row.dataset.search.includes(term))&&(!status||row.dataset.status===status);row.hidden=!show;if(show)visible++});$('#appointmentCount').textContent=`${visible} of ${state.appointments.length} appointments shown`};$('#appointmentSearch').oninput=filterAppointments;$('#appointmentFilterStatus').onchange=filterAppointments}
  if($('#generateButton')&&!$('#genVariants')){$('#genLanguage').closest('.field').insertAdjacentHTML('afterend','<div class="field"><label>Draft variants</label><select id="genVariants"><option value="1">1 draft</option><option value="3" selected>3 variants</option></select></div>');$('#generateButton').textContent='✦ Generate locally';$('#generateButton').insertAdjacentHTML('afterend',' <button class="ghost-button" id="serverGenerateButton">Generate with server AI</button> <span class="pill" id="serverAiStatus">Checking server…</span>');fetch('/api/integrations',{cache:'no-store'}).then(response=>response.json()).then(data=>{const ready=data.integrations?.find(item=>item.id==='openai')?.configured,button=$('#serverGenerateButton'),status=$('#serverAiStatus');button.disabled=!ready;button.title=ready?'Secure server AI is ready':'Add OPENAI_API_KEY in Cloudflare to enable';status.textContent=ready?'Server AI ready':'Server AI setup needed';status.className=`pill ${ready?'green':'orange'}`}).catch(()=>{const button=$('#serverGenerateButton'),status=$('#serverAiStatus');button.disabled=true;status.textContent='Server unavailable';status.className='pill orange'})}
  if($('#forecastChart')){
    const defaults={leads:[14,17,19,18,22,24],revenue:[38,42,47,45,55,64],visits:[720,810,870,940,1080,1284]};
    const refreshForecast=()=>{
      const months=Number($('#forecastPeriod').value),budget=Number($('#budgetLift').value),conversion=Number($('#conversionLift').value),metric=$('#forecastMetric').value;
      $('#budgetLiftValue').textContent=`${budget>=0?'+':''}${budget}%`; $('#conversionLiftValue').textContent=`+${conversion}%`;
      const imported=state.forecastData?.[metric],history=imported?.length>=4?imported:defaults[metric],trend=linearTrend(history),base=history.at(-1),growth=Math.max(-.12,Math.min(.2,trend.slope/Math.max(1,base)));
      const config={leads:{label:'Leads',format:n=>Math.round(n)},revenue:{label:'Revenue',format:n=>`₹${Math.round(n)}K`},visits:{label:'Website visits',format:n=>Math.round(n).toLocaleString('en-IN')}}[metric];
      const conversionRate=Math.max(0,Math.min(100,Number($('#conversionRate').value)||0)),averageValue=Math.max(0,Number($('#averageValue').value)||0),reviewRating=Math.max(1,Math.min(5,Number($('#reviewRating').value)||1)),seoHealth=Math.max(0,Math.min(100,Number($('#seoHealth').value)||0));
      const returns=history.slice(1).map((v,i)=>(v-history[i])/Math.max(1,history[i])),momentum=returns.slice(-3).reduce((a,b)=>a+b,0)/Math.max(1,returns.slice(-3).length),meanReturn=returns.reduce((a,b)=>a+b,0)/Math.max(1,returns.length),volatility=Math.sqrt(returns.reduce((a,b)=>a+Math.pow(b-meanReturn,2),0)/Math.max(1,returns.length));
      const technicalScore=Math.round(clamp(50+growth*220+momentum*120-volatility*130,0,100)),fundamentalScore=Math.round(clamp(conversionRate*.35+(averageValue/5000*100)*.2+(reviewRating/5*100)*.25+seoHealth*.2,0,100)),combinedScore=Math.round(technicalScore*.55+fundamentalScore*.45),modelFactor=.85+combinedScore*.003;
      const scenarioFactor=(1+(budget*.004)+(conversion/100))*modelFactor,season=[1.01,1.04,1.02,1.08,1.12,1.06,1.03,1.05,1.1,1.15,1.08,1.04];
      const baseline=Array.from({length:months},(_,i)=>Math.max(0,base*Math.pow(1+growth,i+1)*season[i]));
      const scenario=baseline.map((v,i)=>v*(1+(scenarioFactor-1)*((i+1)/months)));
      drawForecastChart(history,baseline,scenario,config.format,config.label); drawChannelChart(scenario.reduce((a,b)=>a+b,0),budget);
      const leadHistory=state.forecastData?.leads?.length>=4?state.forecastData.leads:defaults.leads,leadTrend=linearTrend(leadHistory),leadGrowth=Math.max(-.12,Math.min(.2,leadTrend.slope/Math.max(1,leadHistory.at(-1)))),leadBase=leadHistory.at(-1)*Math.pow(1+leadGrowth,months)*months,leadScenario=leadBase*scenarioFactor;
      const bookings=leadScenario*(conversionRate/100);$('#predictedLeads').textContent=Math.round(leadScenario); $('#leadsDelta').textContent=`${scenarioFactor>=1?'↑':'↓'} ${Math.abs(Math.round((scenarioFactor-1)*100))}% combined adjustment`; $('#predictedBookings').textContent=Math.round(bookings); $('#predictedRevenue').textContent=`₹${Math.round(bookings*averageValue/1000)}K`; $('#revenueDelta').textContent=`Across ${months} months`; $('#forecastChartTitle').textContent=`${config.label} forecast`;
      $('#technicalScore').textContent=technicalScore;$('#technicalRing').style.setProperty('--score',technicalScore);$('#fundamentalScore').textContent=fundamentalScore;$('#trendSignal').textContent=growth>.03?'Rising':growth<-.02?'Falling':'Stable';$('#momentumSignal').textContent=momentum>.03?'Positive':momentum<-.03?'Negative':'Neutral';$('#volatilitySignal').textContent=volatility>.16?'High':volatility>.08?'Medium':'Low';const signal=combinedScore>=70?'Growth':combinedScore>=50?'Hold & improve':'Caution';$('#combinedSignal').textContent=`${signal} · ${combinedScore}/100`;$('#combinedSignal').className=`pill ${combinedScore>=70?'green':combinedScore>=50?'orange':''}`;$('#analysisVerdict').innerHTML=combinedScore>=70?'<b>Growth opportunity:</b> signals support measured scaling. Keep review velocity and conversion quality stable.':combinedScore>=50?'<b>Balanced outlook:</b> maintain spend and improve conversion or SEO before scaling aggressively.':'<b>Caution:</b> technical weakness and fundamentals do not yet support higher spend. Fix the weakest inputs first.';
    };
    ['forecastPeriod','forecastMetric','budgetLift','conversionLift','conversionRate','averageValue','reviewRating','seoHealth'].forEach(id=>$('#'+id).addEventListener('input',refreshForecast));
    $('#exportForecast').onclick=()=>{const rows=['Metric,Value',`Period,${$('#forecastPeriod').value} months`,`Budget change,${$('#budgetLift').value}%`,`Conversion improvement,${$('#conversionLift').value}%`,`Predicted leads,${$('#predictedLeads').textContent}`,`Predicted revenue,${$('#predictedRevenue').textContent}`];const blob=new Blob([rows.join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='marketingmind-forecast.csv';a.click();URL.revokeObjectURL(a.href);toast('Forecast exported')};
    $('#downloadTemplate').onclick=()=>downloadText('month,leads,revenue,visits\n2026-01,14,38,720\n2026-02,17,42,810\n2026-03,19,47,870\n2026-04,18,45,940\n2026-05,22,55,1080\n2026-06,24,64,1284','marketingmind-data-template.csv');
    $('#forecastFile').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=parseForecastCsv(reader.result);state.forecastData=parsed.data;state.forecastMonths=parsed.months;save();$('#dataSourceLabel').textContent=`Using ${file.name} · ${parsed.months.length} months imported`;refreshForecast();toast('Historical data imported')}catch(err){toast(err.message)}};reader.readAsText(file)};
    if(state.forecastData)$('#dataSourceLabel').textContent=`Using imported data · ${state.forecastData.leads.length} months saved locally`;
    refreshForecast();
  }
  $('#generateButton')?.addEventListener('click',()=>{let topic=$('#genTopic').value.trim()||'your latest offer',type=$('#genType').value,goal=$('#genGoal').value,language=$('#genLanguage').value,count=Number($('#genVariants').value),drafts=Array.from({length:count},(_,index)=>createLocalDraft(topic,type,goal,language,index)),out=$('#generatedOutput'),channel=type.startsWith('Instagram')?'Instagram':type.startsWith('Facebook')?'Facebook':type.startsWith('Google')?'Google Business':'Blog';logUsage(`${type} · ${count} variant${count===1?'':'s'}`,count);out.style.display='block';out.innerHTML=`<div class="card-header"><div><h2 class="card-title">Your ${language} draft${count===1?'':' variants'}</h2><p class="card-subtitle">Choose, edit and verify before publishing</p></div><div><button class="ghost-button" id="copyDraft">Copy</button> <button class="primary-button" id="saveDraft">Save to planner</button></div></div>${count>1?`<div class="field" style="margin-bottom:12px"><label>Choose variant</label><select id="draftVariant">${drafts.map((_,i)=>`<option value="${i}">Variant ${i+1}</option>`).join('')}</select></div>`:''}<textarea id="draftText" style="width:100%;min-height:190px;font-size:15px;line-height:1.7">${escapeHtml(drafts[0])}</textarea><div class="content-meta" style="margin-top:12px"><span>${type} · ${goal}</span><button class="text-button" id="scheduleDraft">Schedule instead →</button></div>`;$('#draftVariant')?.addEventListener('change',event=>{$('#draftText').value=drafts[Number(event.target.value)]});$('#copyDraft').onclick=()=>navigator.clipboard?.writeText($('#draftText').value).then(()=>toast('Draft copied'));$('#saveDraft').onclick=()=>{state.posts.unshift({title:topic,copy:$('#draftText').value,channel,status:'Draft',date:'Unscheduled',theme:'alt'});save();toast('Selected draft saved to planner')};$('#scheduleDraft').onclick=()=>{let d=modal('Schedule generated draft',`<div class="field"><label>Publish date and time</label><input id="draftDate" type="datetime-local" required></div>`,'Schedule');d.onsubmit=e=>{e.preventDefault();state.posts.unshift({title:topic,copy:$('#draftText').value,channel,status:'Scheduled',date:new Date($('#draftDate').value).toLocaleString(),theme:'third'});save();d.close();toast('Selected draft added to publishing queue')}};});
  $('#serverGenerateButton')?.addEventListener('click',async event=>{const button=event.currentTarget,topic=$('#genTopic').value.trim(),type=$('#genType').value,goal=$('#genGoal').value,language=$('#genLanguage').value;if(!topic){toast('Add a topic or verified offer first');return}button.disabled=true;button.textContent='Generating…';try{const response=await fetch('/api/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({topic,type,goal,language,business:state.business.name,tone:$('#genTone').value})}),data=await response.json();if(!response.ok||!data.ok){toast(data.error==='not_configured'?'Server AI is not configured — use the local generator':'Server AI unavailable — local generator is ready');return}logUsage(`Server AI · ${type}`,Math.max(1,Math.ceil((data.usage?.total_tokens||1)/100)));renderServerDraft(data.text,topic,type,goal,language,data.model)}catch{toast('Server AI unavailable — local generator is ready')}finally{button.disabled=false;button.textContent='Generate with server AI'}});
  $('#auditButton')?.addEventListener('click',seoAuditModal);
  $('#addLead')?.addEventListener('click',()=>{let d=modal('Add a lead',`<div class="form-grid"><div class="field"><label>Name</label><input id="leadName" required></div><div class="field"><label>Phone</label><input id="leadPhone" type="tel"></div><div class="field"><label>Source</label><select id="leadSource"><option>Google</option><option>Instagram</option><option>Website</option><option>Referral</option></select></div><div class="field"><label>Next follow-up</label><input id="leadFollowUp" type="date"></div><div class="field full"><label>Interested in</label><input id="leadService"></div><div class="field full"><label>Notes</label><textarea id="leadNotes" placeholder="Customer preference, enquiry details, next action…"></textarea></div></div>`,'Add lead');d.onsubmit=e=>{e.preventDefault();state.leads.unshift({name:$('#leadName').value,phone:$('#leadPhone').value,source:$('#leadSource').value,service:$('#leadService').value||'Not specified',followUp:$('#leadFollowUp').value,notes:$('#leadNotes').value,status:$('#leadFollowUp').value?'Follow-up':'New',date:'Today'});save();d.close();route('crm');toast('Lead added')};});
  $('#exportLeads')?.addEventListener('click',()=>{const rows=[['name','phone','source','service','status','date','followup','notes'],...state.leads.map(l=>[l.name,l.phone,l.source,l.service,l.status,l.date,l.followUp,l.notes])];downloadText(rows.map(row=>row.map(csvCell).join(',')).join('\n'),'marketingmind-leads.csv');toast('Leads exported')});
  $('#importLeads')?.addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const imported=parseLeadsCsv(reader.result);state.leads=[...imported,...state.leads];save();route('crm');toast(`${imported.length} leads imported`)}catch(error){toast(error.message)}};reader.readAsText(file)});
  $('#exportAppointments')?.addEventListener('click',()=>{const rows=[['date','customer','service','staff','value','status'],...state.appointments.map(a=>[a.date,a.customer,a.service,a.staff,a.value,a.status])];downloadText(rows.map(row=>row.map(csvCell).join(',')).join('\n'),'marketingmind-appointments.csv');toast('Appointments exported')});
  $('#exportSchedule')?.addEventListener('click',()=>{const rows=[['title','channel','status','publish_time','copy'],...state.posts.map(post=>[post.title,post.channel,post.status,post.date,post.copy||''])];downloadText(rows.map(row=>row.map(csvCell).join(',')).join('\n'),'marketingmind-publishing-queue.csv');toast('Publishing queue exported')});
  $('#exportCalendar')?.addEventListener('click',()=>{const active=state.appointments.filter(a=>a.status!=='Cancelled'),events=active.map((a,index)=>{const start=new Date(a.date),end=new Date(start.getTime()+60*60*1000),clean=value=>String(value||'').replace(/([,;\\])/g,'\\$1').replace(/\n/g,'\\n');return ['BEGIN:VEVENT',`UID:marketingmind-${start.getTime()}-${index}@local`,`DTSTAMP:${toIcsDate(new Date())}`,`DTSTART:${toIcsDate(start)}`,`DTEND:${toIcsDate(end)}`,`SUMMARY:${clean(`${a.service} — ${a.customer}`)}`,`DESCRIPTION:${clean(`Staff: ${a.staff||'Unassigned'} | Status: ${a.status} | Value: INR ${a.value||0}`)}`,`LOCATION:${clean(state.business.address)}`,'END:VEVENT'].join('\r\n')}).join('\r\n');downloadText(`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//MarketingMind AI//Appointments//EN\r\nCALSCALE:GREGORIAN\r\n${events}\r\nEND:VCALENDAR`,'marketingmind-appointments.ics');toast(`${active.length} appointments exported to calendar`)});
  $('#settingsForm')?.addEventListener('submit',e=>{e.preventDefault();state.business=Object.fromEntries(new FormData(e.currentTarget));save();updateShellStatus();toast('Business profile saved')});
  $('#exportBackup')?.addEventListener('click',()=>{const backup={app:'MarketingMind AI',version:1,exportedAt:new Date().toISOString(),data:state};downloadText(JSON.stringify(backup,null,2),`marketingmind-backup-${new Date().toISOString().slice(0,10)}.json`);toast('Workspace backup exported')});
  $('#importBackup')?.addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const backup=JSON.parse(reader.result);const incoming=backup?.data||backup;if(!incoming?.business||!Array.isArray(incoming.leads)||!Array.isArray(incoming.posts))throw new Error('This is not a valid MarketingMind backup');state=incoming;state.localSeoChecks||=[true,true,true,true,true,true,false,false];state.appointments||=[];state.usage||=[];save();route('settings');toast('Workspace backup restored')}catch(error){toast(error.message||'Backup could not be imported')}};reader.readAsText(file)});
  $('#clearUsage')?.addEventListener('click',()=>{if(!confirm('Clear local usage history?'))return;state.usage=[];save();route('credits');toast('Usage history cleared')});
  $('#exportUsage')?.addEventListener('click',()=>{const rows=[['date','action','provider','credits','estimated_cost_inr'],...state.usage.map(row=>[row.date,row.action,'Local engine',row.credits,0])];downloadText(rows.map(row=>row.map(csvCell).join(',')).join('\n'),'marketingmind-usage-report.csv');toast('Usage report exported')});
  $$('[data-edit-post]').forEach(button=>button.onclick=()=>editPostModal(Number(button.dataset.editPost)));
  $$('[data-delete-post]').forEach(button=>button.onclick=()=>{if(!confirm('Remove this content item?'))return;state.posts.splice(Number(button.dataset.deletePost),1);save();route('scheduler');toast('Content removed')});
  $$('[data-lead-status]').forEach(select=>select.onchange=()=>{state.leads[Number(select.dataset.leadStatus)].status=select.value;state.leads[Number(select.dataset.leadStatus)].date='Today';save();route('crm');toast('Lead status updated')});
  $$('[data-edit-lead]').forEach(button=>{if(!button.previousElementSibling?.matches('[data-message-lead]'))button.insertAdjacentHTML('beforebegin',`<button class="text-button" data-message-lead="${button.dataset.editLead}">Message</button> `)});
  $$('[data-message-lead]').forEach(button=>button.onclick=()=>leadFollowUpModal(Number(button.dataset.messageLead)));
  $$('[data-delete-lead]').forEach(button=>button.onclick=()=>{if(!confirm('Remove this lead from the local CRM?'))return;state.leads.splice(Number(button.dataset.deleteLead),1);save();route('crm');toast('Lead removed')});
  $$('[data-edit-lead]').forEach(button=>button.onclick=()=>editLeadModal(Number(button.dataset.editLead)));
  $$('[data-appointment-status]').forEach(select=>select.onchange=()=>{state.appointments[Number(select.dataset.appointmentStatus)].status=select.value;save();route('appointments');toast('Appointment status updated')});
  $$('[data-edit-appointment]').forEach(button=>{if(!button.previousElementSibling?.matches('[data-remind-appointment]'))button.insertAdjacentHTML('beforebegin',`<button class="text-button" data-remind-appointment="${button.dataset.editAppointment}">Reminder</button> `)});
  $$('[data-remind-appointment]').forEach(button=>button.onclick=()=>appointmentReminderModal(Number(button.dataset.remindAppointment)));
  $$('[data-delete-appointment]').forEach(button=>button.onclick=()=>{if(!confirm('Remove this appointment?'))return;state.appointments.splice(Number(button.dataset.deleteAppointment),1);save();route('appointments');toast('Appointment removed')});
  $$('[data-edit-appointment]').forEach(button=>button.onclick=()=>editAppointmentModal(Number(button.dataset.editAppointment)));
  $$('[data-check]').forEach(b=>b.onclick=()=>{let index=Number(b.dataset.check);state.localSeoChecks[index]=!state.localSeoChecks[index];save();route('local')});
}
function drawForecastChart(history,baseline,scenario,format,label){const el=$('#forecastChart'),w=Math.max(560,el.clientWidth||760),h=310,p={l:58,r:24,t:24,b:42},all=[...history,...baseline,...scenario],min=Math.min(...all)*.88,max=Math.max(...all)*1.1,total=history.length+baseline.length,x=i=>p.l+i*(w-p.l-p.r)/(total-1),y=v=>p.t+(max-v)*(h-p.t-p.b)/(max-min),path=arr=>arr.map((v,i)=>`${i?'L':'M'} ${x(i)} ${y(v)}`).join(' '),futureStart=history.length-1,fullBase=[history.at(-1),...baseline],fullScenario=[history.at(-1),...scenario],ticks=Array.from({length:5},(_,i)=>min+(max-min)*i/4);el.innerHTML=`<svg viewBox="0 0 ${w} ${h}" aria-hidden="true"><rect class="forecast-zone" x="${x(futureStart)}" y="${p.t}" width="${w-p.r-x(futureStart)}" height="${h-p.t-p.b}"></rect>${ticks.map(v=>`<line class="grid-line" x1="${p.l}" y1="${y(v)}" x2="${w-p.r}" y2="${y(v)}"></line><text class="axis-label" x="${p.l-9}" y="${y(v)+4}" text-anchor="end">${format(v)}</text>`).join('')}<line class="axis-line" x1="${p.l}" y1="${h-p.b}" x2="${w-p.r}" y2="${h-p.b}"></line><path class="chart-line actual-line" d="${path(history)}"></path><path class="chart-line baseline-line" d="${fullBase.map((v,i)=>`${i?'L':'M'} ${x(futureStart+i)} ${y(v)}`).join(' ')}"></path><path class="chart-line scenario-line" d="${fullScenario.map((v,i)=>`${i?'L':'M'} ${x(futureStart+i)} ${y(v)}`).join(' ')}"></path>${scenario.map((v,i)=>`<circle class="scenario-point" cx="${x(history.length+i)}" cy="${y(v)}" r="4"><title>Month ${i+1}: ${format(v)} ${label}</title></circle>`).join('')}<text class="axis-caption" x="${p.l}" y="${h-13}">6 months actual</text><text class="axis-caption" x="${w-p.r}" y="${h-13}" text-anchor="end">${baseline.length} months predicted</text><text class="forecast-label" x="${x(futureStart)+10}" y="${p.t+17}">FORECAST</text></svg>`}
function drawChannelChart(total,budget){const channels=[['Google',.42],['Instagram',.31],['Website',.17],['Referral',.10]],adjust=1+budget*.002;$('#channelChart').innerHTML=channels.map(([name,share])=>{const value=Math.round(total*share*adjust),width=Math.round(share*100);return `<div class="channel-row"><div><b>${name}</b><span>${value} leads · ${width}%</span></div><div class="channel-track"><span style="width:${width}%"></span></div></div>`}).join('')}
function linearTrend(values){const n=values.length,sumX=n*(n-1)/2,sumY=values.reduce((a,b)=>a+b,0),sumXY=values.reduce((a,b,i)=>a+b*i,0),sumXX=values.reduce((a,b,i)=>a+i*i,0),den=n*sumXX-sumX*sumX,slope=den?(n*sumXY-sumX*sumY)/den:0;return {slope,intercept:(sumY-slope*sumX)/n}}
function parseForecastCsv(text){const rows=text.trim().split(/\r?\n/).map(r=>r.split(',').map(v=>v.trim())),headers=rows.shift().map(x=>x.toLowerCase()),required=['month','leads','revenue','visits'];if(!required.every(x=>headers.includes(x)))throw new Error('CSV needs month, leads, revenue and visits columns');if(rows.length<4)throw new Error('Import at least 4 months of data');const index=Object.fromEntries(required.map(x=>[x,headers.indexOf(x)])),data={leads:[],revenue:[],visits:[]},months=[];rows.forEach((row,i)=>{months.push(row[index.month]);['leads','revenue','visits'].forEach(key=>{const value=Number(row[index[key]]);if(!Number.isFinite(value)||value<0)throw new Error(`Invalid ${key} value on row ${i+2}`);data[key].push(value)})});return {months,data}}
function parseCsvLine(line){const cells=[];let value='',quoted=false;for(let i=0;i<line.length;i++){const char=line[i];if(char==='"'&&quoted&&line[i+1]==='"'){value+='"';i++}else if(char==='"'){quoted=!quoted}else if(char===','&&!quoted){cells.push(value.trim());value=''}else value+=char}cells.push(value.trim());return cells}
function parseLeadsCsv(text){const rows=text.trim().split(/\r?\n/).filter(Boolean).map(parseCsvLine),headers=rows.shift()?.map(x=>x.toLowerCase()),required=['name','source','service'];if(!headers||!required.every(x=>headers.includes(x)))throw new Error('CSV needs name, source and service columns');const at=key=>headers.indexOf(key),get=(row,key)=>at(key)>=0?row[at(key)]||'':'',valid=['New','Follow-up','Booked','Lost'];const leads=rows.map((row,index)=>{const name=get(row,'name').trim();if(!name)throw new Error(`Missing name on row ${index+2}`);const status=get(row,'status')||'New';return {name,phone:get(row,'phone'),source:get(row,'source')||'Imported',service:get(row,'service')||'Not specified',status:valid.includes(status)?status:'New',date:get(row,'date')||'Imported',followUp:get(row,'followup'),notes:get(row,'notes')}});if(!leads.length)throw new Error('No lead rows found');return leads}
function csvCell(value){const text=String(value??'');return /[",\n]/.test(text)?`"${text.replaceAll('"','""')}"`:text}
function toIcsDate(date){return date.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}
function downloadText(text,name){const type=name.endsWith('.json')?'application/json':name.endsWith('.ics')?'text/calendar':'text/csv',blob=new Blob([text],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function clamp(value,min,max){return Math.max(min,Math.min(max,value))}
document.addEventListener('click',e=>{let routeEl=e.target.closest('[data-route]'),action=e.target.closest('[data-action]');if(routeEl){e.preventDefault();route(routeEl.dataset.route)}if(action){let a=action.dataset.action;if(a==='create-content')contentModal();else if(a==='placeholder')toast('Integration placeholder — ready for API connection');else if(a==='review-link')reviewRequestModal();else if(a==='appointment')appointmentModal()}});
$('#menuButton').onclick=()=>$('#sidebar').classList.toggle('open');
$('#collapseButton').onclick=()=>$('#sidebar').classList.toggle('open');
$('#searchButton').onclick=()=>{const modules=nav.flatMap(([,items])=>items),renderResults=query=>{const term=query.trim().toLowerCase(),matches=modules.filter(([route,,title])=>!term||`${title} ${route}`.toLowerCase().includes(term));$('#quickResults').innerHTML=matches.length?matches.map(([route,icon,title])=>`<button type="button" class="search-result" data-search-route="${route}"><span>${icon}</span><b>${title}</b><small>${titles[route]}</small></button>`).join(''):'<div class="empty-search">No matching module</div>';$$('[data-search-route]').forEach(button=>button.onclick=()=>{d.close();route(button.dataset.searchRoute)})};let d=modal('Jump to a module',`<div class="field"><label>Search workspace</label><input id="quickSearch" autofocus autocomplete="off" placeholder="Try SEO, CRM, content…"></div><div class="search-results" id="quickResults"></div>`,'Close');renderResults('');$('#quickSearch').oninput=event=>renderResults(event.target.value);d.onsubmit=event=>{event.preventDefault();const first=$('[data-search-route]');if(first){d.close();route(first.dataset.searchRoute)}}};
$('#notificationButton').onclick=notificationModal;
window.addEventListener('hashchange',()=>route(location.hash.slice(1)));
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchButton').click()}});
renderNav();route(location.hash.slice(1)||'dashboard');
let installPrompt=null;
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;$('#installApp').hidden=false});
$('#installApp').onclick=async()=>{if(!installPrompt)return;await installPrompt.prompt();installPrompt=null;$('#installApp').hidden=true};
window.addEventListener('appinstalled',()=>toast('MarketingMind installed'));
if('serviceWorker' in navigator&&location.protocol==='https:')navigator.serviceWorker.register('/sw.js').catch(()=>{});

