(() => {
'use strict';
const $=id=>document.getElementById(id),video=$('preview'),canvas=$('renderCanvas'),music=$('musicPreview');
let inputURL,outputURL,musicURL,recorder,stream,timer,raf,busy=false,cancelled=false,previewing=false,clips=[],activeClip=0,audioContext,audioDestination,videoGain,musicGain;
const status=t=>$('status').textContent=t;
const range=()=>{const start=Number($('start').value),end=Number($('end').value);if(!Number.isFinite(start)||!Number.isFinite(end)||start<0||end<=start||end>video.duration+.01)throw Error('Choose a valid start and end within the video duration.');return{start,end}};
const seek=time=>new Promise((resolve,reject)=>{if(Math.abs(video.currentTime-time)<.01)return resolve();let timeout;const clean=()=>{clearTimeout(timeout);video.removeEventListener('seeked',done);video.removeEventListener('error',fail)},done=()=>{clean();resolve()},fail=()=>{clean();reject(Error('Cannot seek this video. Try another file.'))};timeout=setTimeout(fail,10000);video.addEventListener('seeked',done,{once:true});video.addEventListener('error',fail,{once:true});video.currentTime=time});
function renderClips(){const box=$('clipList');if(!box)return;box.innerHTML=clips.map((c,i)=>`<button type="button" class="ghost-button" data-clip="${i}" style="margin:4px;${i===activeClip?'font-weight:700':''}">${i+1}. ${c.name}</button>`).join('');box.querySelectorAll('[data-clip]').forEach(b=>b.onclick=()=>loadClip(Number(b.dataset.clip)))}
function loadClip(i){if(!clips[i]||busy)return;activeClip=i;video.pause();previewing=false;resetOutput();if(inputURL)URL.revokeObjectURL(inputURL);inputURL=URL.createObjectURL(clips[i].file);video.src=inputURL;status(`Reading clip ${i+1} of ${clips.length}…`);renderClips()}
function loadClipReady(i){return new Promise((resolve,reject)=>{loadClip(i);if(video.readyState>=1)return resolve();const done=()=>{clean();resolve()},fail=()=>{clean();reject(Error(`Cannot load clip ${i+1}.`))},clean=()=>{video.removeEventListener('loadedmetadata',done);video.removeEventListener('error',fail)};video.addEventListener('loadedmetadata',done,{once:true});video.addEventListener('error',fail,{once:true})})}
function audioMix(){if(!audioContext){audioContext=new (window.AudioContext||window.webkitAudioContext)();audioDestination=audioContext.createMediaStreamDestination();videoGain=audioContext.createGain();musicGain=audioContext.createGain();audioContext.createMediaElementSource(video).connect(videoGain).connect(audioDestination);audioContext.createMediaElementSource(music).connect(musicGain).connect(audioDestination)}videoGain.gain.value=$('mute').checked?0:Number($('originalVolume').value);musicGain.gain.value=Number($('musicVolume').value);return audioDestination.stream}
function resetOutput(){$('download').hidden=true;$('download').removeAttribute('href');if(outputURL)URL.revokeObjectURL(outputURL);outputURL=null}
function cleanup(){clearInterval(timer);cancelAnimationFrame(raf);video.pause();music.pause();stream?.getTracks().forEach(t=>t.stop());stream=null;recorder=null;busy=false;video.controls=true;$('source').disabled=false;$('controls').disabled=!Number.isFinite(video.duration);$('cancel').hidden=true;$('progress').hidden=true}
function abort(message){cancelled=true;status(message);if(recorder&&recorder.state!=='inactive')recorder.stop();else cleanup()}
function size(){const mode=$('aspect').value,sw=video.videoWidth,sh=video.videoHeight;if(mode==='source')return{w:sw,h:sh};const [a,b]=mode.split(':').map(Number),max=1080;let w,h;if(a>=b){w=Math.min(max,sw);h=Math.round(w*b/a)}else{h=Math.min(max,sh);w=Math.round(h*a/b)}w-=w%2;h-=h%2;return{w:Math.max(2,w),h:Math.max(2,h)}}
function draw(){if(!busy)return;const w=canvas.width,h=canvas.height,sw=video.videoWidth,sh=video.videoHeight,scale=Math.max(w/sw,h/sh),dw=sw*scale,dh=sh*scale;const ctx=canvas.getContext('2d');ctx.fillStyle='#000';ctx.fillRect(0,0,w,h);ctx.drawImage(video,(w-dw)/2,(h-dh)/2,dw,dh);raf=requestAnimationFrame(draw)}
$('source').onchange=()=>{const files=[...$('source').files];if(!files.length)return;clips=files.map(file=>({file,name:file.name}));activeClip=0;loadClip(0)};
video.onloadedmetadata=()=>{if(!Number.isFinite(video.duration)||video.duration<=0)return status('This file has no usable duration. Try another video.');const saved=clips[activeClip]?.range;$('start').value=String(saved?.start??0);$('end').value=String(saved?.end??video.duration);$('start').max=$('end').max=String(video.duration);$('controls').disabled=false;status(`Ready · ${video.duration.toFixed(2)} seconds · ${video.videoWidth}×${video.videoHeight}.`)};
video.onerror=()=>busy?abort('Video decoding failed; export cancelled.'):( $('controls').disabled=true,status('This browser cannot play this video. Try an MP4 or WebM file.') );
for(const id of ['start','end','aspect','mute','originalVolume','musicVolume'])$(id).onchange=()=>{previewing=false;video.pause();resetOutput();if(videoGain){videoGain.gain.value=$('mute').checked?0:Number($('originalVolume').value);musicGain.gain.value=Number($('musicVolume').value)}};
$('music').onchange=()=>{if(musicURL)URL.revokeObjectURL(musicURL);const file=$('music').files[0];if(!file){music.removeAttribute('src');music.hidden=true;return}musicURL=URL.createObjectURL(file);music.src=musicURL;music.hidden=false;music.loop=$('loopMusic').checked;status('Added audio ready for preview and export.')};$('loopMusic').onchange=()=>music.loop=$('loopMusic').checked;
$('play').onclick=async()=>{try{const{start}=range();await seek(start);video.muted=$('mute').checked;previewing=true;await video.play()}catch(e){previewing=false;status(e.message)}};
video.ontimeupdate=()=>{if(previewing&&video.currentTime>=Number($('end').value)){video.pause();previewing=false}};
$('split').onclick=()=>{try{const {start,end}=range(),at=video.currentTime;if(at<=start+.05||at>=end-.05)throw Error('Move the playhead inside the selected range before splitting.');const original=clips[activeClip];if(!original)throw Error('Choose a clip first.');const left={...original,name:`${original.name} · A`,range:{start,end:at}},right={...original,name:`${original.name} · B`,range:{start:at,end}};clips.splice(activeClip,1,left,right);renderClips();$('start').value=String(left.range.start);$('end').value=String(left.range.end);status('Clip split into two timeline items. Select either part to continue editing.')}catch(e){status(e.message)}};
$('export').onclick=async()=>{if(busy)return;try{const{start,end}=range();if(!window.MediaRecorder||!canvas.captureStream)throw Error('Video export needs a recent desktop Chrome, Edge or Firefox browser.');const mime=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm','video/mp4'].find(t=>MediaRecorder.isTypeSupported(t));if(!mime)throw Error('No supported video export format was found.');busy=true;cancelled=false;previewing=false;resetOutput();$('controls').disabled=true;$('source').disabled=true;video.controls=false;$('cancel').hidden=false;video.pause();await seek(start);if(cancelled)return cleanup();const s=size();canvas.width=s.w;canvas.height=s.h;const canvasStream=canvas.captureStream(30);stream=canvasStream;audioMix().getAudioTracks().forEach(t=>stream.addTrack(t));recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:5000000});const chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onerror=()=>abort('Recording failed; no finished export was created.');recorder.onstop=()=>{if(!cancelled&&chunks.length){const blob=new Blob(chunks,{type:mime});outputURL=URL.createObjectURL(blob);$('download').href=outputURL;$('download').download=`marketingmind-edit.${mime.startsWith('video/mp4')?'mp4':'webm'}`;$('download').hidden=false;status(`Export ready · ${s.w}×${s.h}. Download and review before publishing.`)}else if(!cancelled)status('No video data was recorded. Try another browser.');cleanup()};video.muted=false;video.playbackRate=1;if($('music').files[0]){music.currentTime=0;music.loop=$('loopMusic').checked;await music.play()}recorder.start(250);draw();await video.play();$('progress').hidden=false;status('Exporting… Keep this tab visible.');timer=setInterval(()=>{$('progress').value=Math.min(1,(video.currentTime-start)/(end-start));if(video.currentTime>=end||video.ended){clearInterval(timer);video.pause();if(recorder?.state==='recording')recorder.stop()}},40)}catch(e){abort(e.message)}};
$('exportTimeline').onclick=async()=>{if(busy||!clips.length)return;try{if(!window.MediaRecorder||!canvas.captureStream)throw Error('Timeline export needs a recent desktop Chrome, Edge or Firefox browser.');const mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm','video/mp4'].find(t=>MediaRecorder.isTypeSupported(t));if(!mime)throw Error('No supported timeline export format was found.');busy=true;cancelled=false;previewing=false;resetOutput();$('controls').disabled=true;$('source').disabled=true;video.controls=false;$('cancel').hidden=false;await loadClipReady(0);const s=size();canvas.width=s.w;canvas.height=s.h;stream=canvas.captureStream(30);audioMix().getAudioTracks().forEach(t=>stream.addTrack(t));recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:5000000});const chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onerror=()=>abort('Timeline recording failed.');recorder.onstop=()=>{if(!cancelled&&chunks.length){const blob=new Blob(chunks,{type:mime});outputURL=URL.createObjectURL(blob);$('download').href=outputURL;$('download').download=`marketingmind-timeline.${mime.startsWith('video/mp4')?'mp4':'webm'}`;$('download').hidden=false;status('Full timeline export ready. Review it before publishing.')}cleanup()};recorder.start(250);draw();if($('music').files[0]){music.currentTime=0;music.loop=$('loopMusic').checked;await music.play()}$('progress').hidden=false;const total=clips.reduce((sum,c)=>sum+Math.max(.01,(c.range?.end??0)-(c.range?.start??0)),0)||clips.length;let completed=0;for(let i=0;i<clips.length&&!cancelled;i++){await loadClipReady(i);const clip=clips[i],start=clip.range?.start??0,end=clip.range?.end??video.duration;if(end<=start)continue;await seek(start);status(`Exporting timeline · clip ${i+1} of ${clips.length}…`);await video.play();await new Promise(resolve=>{const tick=setInterval(()=>{const part=Math.max(0,Math.min(end-start,video.currentTime-start));$('progress').value=Math.min(1,(completed+part)/Math.max(total,.01));if(video.currentTime>=end||video.ended||cancelled){clearInterval(tick);video.pause();resolve()}},30)});completed+=end-start}if(recorder?.state==='recording')recorder.stop()}catch(e){abort(e.message)}};
$('cancel').onclick=()=>abort('Export cancelled. Your source video is unchanged.');
document.addEventListener('visibilitychange',()=>{if(document.hidden&&busy)abort('Export cancelled because the tab was hidden. Keep it visible and try again.')});
window.addEventListener('beforeunload',e=>{if(busy){e.preventDefault();e.returnValue=''}});
})();
