import {apiHeaders,authenticated,baseUrl,sameOrigin} from '../_shared/supabase.js';
import {open,seal} from '../_shared/provider-crypto.js';
const json=(body,status=200)=>Response.json(body,{status,headers:{'cache-control':'private, no-store','x-content-type-options':'nosniff'}}),MAX_BYTES=100*1024*1024;
async function saved(env,token,id){const response=await fetch(`${baseUrl(env)}/rest/v1/mm_provider_connections?owner_id=eq.${encodeURIComponent(id)}&provider=eq.youtube&select=encrypted_credentials&limit=1`,{headers:apiHeaders(env,token)});return response.ok?(await response.json())[0]:null}
const safeVideoUrl=value=>{try{const url=new URL(value);if(url.protocol!=='https:'||url.username||url.password)return null;const host=url.hostname.toLowerCase();if(host==='localhost'||host.endsWith('.local')||/^127\.|^10\.|^192\.168\.|^169\.254\.|^0\.|^::1$/.test(host)||/^172\.(1[6-9]|2\d|3[01])\./.test(host))return null;return url}catch{return null}};
async function credentialsForSession(context,session){const row=await saved(context.env,session.access,session.user.id);if(!row)return null;let credential=await open(row.encrypted_credentials,context.env.PROVIDER_TOKEN_ENCRYPTION_KEY);if(credential.expiresAt<Date.now()+60000&&credential.refreshToken){const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:context.env.GOOGLE_CLIENT_ID,client_secret:context.env.GOOGLE_CLIENT_SECRET,refresh_token:credential.refreshToken,grant_type:'refresh_token'})}),token=await response.json();if(!response.ok)throw new Error('token_refresh_failed');credential={...credential,accessToken:token.access_token,expiresAt:Date.now()+Number(token.expires_in||3600)*1000};const encrypted=await seal(credential,context.env.PROVIDER_TOKEN_ENCRYPTION_KEY);await fetch(`${baseUrl(context.env)}/rest/v1/mm_provider_connections?owner_id=eq.${encodeURIComponent(session.user.id)}&provider=eq.youtube`,{method:'PATCH',headers:{...apiHeaders(context.env,session.access),prefer:'return=minimal'},body:JSON.stringify({encrypted_credentials:encrypted,updated_at:new Date().toISOString()})})}return credential}
async function credentials(context){return credentialsForSession(context,await authenticated(context))}
export async function onRequestPost(context){
  if(!sameOrigin(context.request))return json({ok:false,error:'invalid_origin'},403);const session=await authenticated(context);if(!session.user)return json({ok:false,error:'sign_in_required'},401);let input;try{input=await context.request.json()}catch{return json({ok:false,error:'invalid_json'},400)}
  const source=safeVideoUrl(String(input.videoUrl||'')),title=String(input.title||'').trim(),description=String(input.description||'').trim(),privacy=String(input.privacy||'private'),allowedHosts=String(context.env.YOUTUBE_VIDEO_SOURCE_HOSTS||'').split(',').map(value=>value.trim().toLowerCase()).filter(Boolean);if(input.confirm!==true)return json({ok:false,error:'explicit_confirmation_required'},400);if(!source)return json({ok:false,error:'invalid_video_url'},400);if(!allowedHosts.includes(source.hostname.toLowerCase()))return json({ok:false,error:'video_source_host_not_approved'},403);if(!title||title.length>100||description.length>5000||!['private','unlisted','public'].includes(privacy))return json({ok:false,error:'invalid_metadata'},400);
  try{const credential=await credentials(context,session.user.id);if(!credential)return json({ok:false,error:'youtube_not_connected'},409);const sourceResponse=await fetch(source,{redirect:'error',headers:{accept:'video/*,application/octet-stream'}});if(!sourceResponse.ok||!sourceResponse.body)throw new Error('video_fetch_failed');const type=String(sourceResponse.headers.get('content-type')||'').split(';')[0].toLowerCase(),length=Number(sourceResponse.headers.get('content-length')||0);if(!(type.startsWith('video/')||type==='application/octet-stream'))throw new Error('source_is_not_video');if(!length)throw new Error('video_size_required');if(length>MAX_BYTES)throw new Error('video_exceeds_100mb_mvp_limit');const start=await fetch('https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet%2Cstatus',{method:'POST',headers:{authorization:`Bearer ${credential.accessToken}`,'content-type':'application/json; charset=UTF-8','x-upload-content-length':String(length),'x-upload-content-type':type},body:JSON.stringify({snippet:{title,description,categoryId:'22'},status:{privacyStatus:privacy}})}),startData=await start.json().catch(()=>({})),location=start.headers.get('location');if(!start.ok||!location)throw new Error(startData.error?.message||'upload_session_failed');const uploaded=await fetch(location,{method:'PUT',headers:{authorization:`Bearer ${credential.accessToken}`,'content-type':type,'content-length':String(length)},body:sourceResponse.body}),data=await uploaded.json().catch(()=>({}));if(!uploaded.ok)throw new Error(data.error?.message||'youtube_upload_failed');return json({ok:true,video:{id:data.id,title:data.snippet?.title||title,privacy:data.status?.privacyStatus||privacy,url:`https://youtu.be/${data.id}`}})}catch(error){return json({ok:false,error:'youtube_upload_failed',message:String(error.message||'Upload failed').slice(0,200)},502)}
}
export function onRequest(){return json({ok:false,error:'method_not_allowed'},405)}

